### ISSUE TITLE
VCF format error

### ISSUE THREAD

**Issue by Addicted-to-coding** [ACEnglish/truvari#100]
**Version** : 3.1.0

Error while using vcf file: We get the following error while trying to run Truvari bench:

ValueError: file `b'STANDARD_HIGHCONF_HG002_SVs_Tier1_v0.6.vcf.gz'` does not have valid header (mode=`b'r'`) - is it VCF/BCF format?

Our vcf file looks like this:

<img width="751" alt="image" src="https://user-images.githubusercontent.com/28642161/157480529-7990fcfb-c43c-484b-930d-0e6e2eac3a54.png">

Can you please help?

**Comment by ACEnglish** [comment]
Hello,

Have you tried the tool described in the [wiki](https://github.com/ACEnglish/truvari/wiki#before-you-start)? If so, what warnings, if any, did it give about your VCF?

**Comment by aditya-sarkar441** [comment]
Hi,

Yes, I have tried the usage_vcf tool on the vcfs, and it was giving the same error as above.

**Comment by ACEnglish** [comment]
This appears to be a mistake made by the tool that produced your VCFs.

From what I can tell, the file is missing FORMAT and SAMPLE columns. Those two columns should be present in the header `#CHROM` line and at minimum the FORMAT `GT` should be present, even if it is `.`. This means it will also need to have a format tag added of `##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">`. 
Also, the VCF appears to be missing `##contig=<ID=1,length=12345>` definitions. See the [vcf format specification](https://samtools.github.io/hts-specs/VCFv4.2.pdf) for details. The contig definitions aren't required by VCF specs, but if you're not using a `--includebed` are required by Truvari.
