### ISSUE TITLE
Truvari giving incorrect vcf format error

### ISSUE THREAD

**Issue by aditya-sarkar441** [ACEnglish/truvari#101]
Hi,

I tried to run Truvari on the bam files and got this error : ValueError: file `b'STANDARD_HIGHCONF_HG002_SVs_Tier1_v0.6.vcf.gz'` does not have valid header (mode=`b'r'`) - is it VCF/BCF format? 

This is the header : 

##fileformat=VCFv4.2
##fileDate=20090805
##source=myImputationProgramV3.1
##reference=file:///seq/references/1000GenomesPilot-NCBI36.fasta
##contig=<ID=20,length=62435964,assembly=B36,md5=f126cdf8a6e0c7f379d618ff66beb2da,species="Homo sapiens",taxonomy=x>
##phasing=partial
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of Samples With Data">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency">
##INFO=<ID=AA,Number=1,Type=String,Description="Ancestral Allele">
##INFO=<ID=DB,Number=0,Type=Flag,Description="dbSNP membership, build 129">
##INFO=<ID=H2,Number=0,Type=Flag,Description="HapMap2 membership">
##FILTER=<ID=q10,Description="Quality below 10">
##FILTER=<ID=s50,Description="Less than 50% of samples have data">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=HQ,Number=2,Type=Integer,Description="Haplotype Quality">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO

**Comment by ACEnglish** [comment]
Please see #100

**Comment by aditya-sarkar441** [comment]
But we don't have any information about the Format and Sample columns.

**Comment by ACEnglish** [comment]
Yes, that's why I suggested:

> Those two columns should be present in the header #CHROM line and at minimum the FORMAT GT should be present, even if it is .. This means it will also need to have a format tag added of ##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">.
> Also, the VCF appears to be missing ##contig=<ID=1,length=12345> definitions. See the [vcf format specification](https://samtools.github.io/hts-specs/VCFv4.2.pdf) for details. The contig definitions aren't required by VCF specs, but if you're not using a --includebed are required by Truvari.

So just add  `FORMAT\tSAMPLE` to the header and `GT\t.` to each variant. Again, "This appears to be a mistake made by the tool that produced your VCFs.". If you're still having issues with it, the maintainers of the tool should have the answers to your qustions.

**Comment by aditya-sarkar441** [comment]
Thanks, I followed all the steps you mentioned and it worked. However, it gave me a new error : 
TypeError: '>=' not supported between instances of 'int' and 'NoneType'

Can you please help me with this?

**Comment by ACEnglish** [comment]
I would need to see the full error to have any idea what part of the VCF is now breaking.

But one of your INFO or perhaps FORMAT fields is not defined correctly or at all. My guess would be you're missing SVLEN

**Comment by aditya-sarkar441** [comment]
Here's the error : I have also attached my vcfs in .txt format. Github is not accepted .vcf. Thanks again :)

2022-03-14 14:14:59,453 [INFO] Running /u/home/m/mdistler/project-jflint/anaconda3/bin/truvari bench -b STANDARD_HIGHCONF_HG002_SVs_Tier2_v0.6.vcf.gz -c smoove_chrall_10_FP_TP.vcf.gz -f /u/home/m/mdistler/scratch/hs37d5.fa -o output_dir/
2022-03-14 14:14:59,453 [INFO] Params:
{
    "base": "STANDARD_HIGHCONF_HG002_SVs_Tier2_v0.6.vcf.gz",
    "comp": "smoove_chrall_10_FP_TP.vcf.gz",
    "output": "output_dir/",
    "reference": "/u/home/m/mdistler/scratch/hs37d5.fa",
    "giabreport": false,
    "debug": false,
    "prog": false,
    "refdist": 500,
    "pctsim": 0.7,
    "buffer": 0.1,
    "pctsize": 0.7,
    "pctovl": 0.0,
    "typeignore": false,
    "use_lev": false,
    "gtcomp": false,
    "bSample": null,
    "cSample": null,
    "sizemin": 50,
    "sizefilt": 30,
    "sizemax": 50000,
    "passonly": false,
    "no_ref": false,
    "includebed": null,
    "multimatch": false
}
2022-03-14 14:14:59,496 [INFO] Creating call interval tree for overlap search
Traceback (most recent call last):
  File "/u/home/m/mdistler/project-jflint/anaconda3/bin/truvari", line 33, in <module>
    sys.exit(load_entry_point('Truvari==3.0.0', 'console_scripts', 'truvari')())
  File "/u/home/m/mdistler/project-jflint/anaconda3/lib/python3.8/site-packages/Truvari-3.0.0-py3.8.egg/truvari/__main__.py", line 64, in main
  File "/u/home/m/mdistler/project-jflint/anaconda3/lib/python3.8/site-packages/Truvari-3.0.0-py3.8.egg/truvari/bench.py", line 439, in bench_main
  File "/u/home/m/mdistler/project-jflint/anaconda3/lib/python3.8/site-packages/Truvari-3.0.0-py3.8.egg/truvari/genome_tree.py", line 21, in __init__
  File "/u/home/m/mdistler/project-jflint/anaconda3/lib/python3.8/site
[STANDARD_HIGHCONF_HG002_SVs_Tier2_v0.6.txt](https://github.com/ACEnglish/truvari/files/8248571/STANDARD_HIGHCONF_HG002_SVs_Tier2_v0.6.txt)
[smoove_chrall_10_FP_TP.txt](https://github.com/ACEnglish/truvari/files/8248573/smoove_chrall_10_FP_TP.txt)
-packages/Truvari-3.0.0-py3.8.egg/truvari/genome_tree.py", line 52, in __build_tree
  File "/u/home/m/mdistler/project-jflint/anaconda3/lib/python3.8/site-packages/intervaltree/intervaltree.py", line 343, in addi
    return self.add(Interval(begin, end, data))
  File "/u/home/m/mdistler/project-jflint/anaconda3/lib/python3.8/site-packages/intervaltree/intervaltree.py", line 323, in add
    if interval.is_null():
  File "/u/home/m/mdistler/project-jflint/anaconda3/lib/python3.8/site-packages/intervaltree/interval.py", line 116, in is_null
    return self.begin >= self.end
TypeError: '>=' not supported between instances of 'int' and 'NoneType'

**Comment by ACEnglish** [comment]
```python
>>> import pysam
>>> v = pysam.VariantFile("smoove_chrall_10_FP_TP.txt")
>>> for entry in v:
...     break
...
[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse_info] INFO 'SVTYPE' is not defined in the header, assuming Type=String
[W::vcf_parse_info] INFO 'SVLEN' is not defined in the header, assuming Type=String
[W::vcf_parse_info] INFO 'END' is not defined in the header, assuming Type=String
```

Those three fields are not defined in the VCF's header and the `##contig` is also not defined.  These are all issues with the VCF, which Truvari did not create. These things need to be addressed to the maintainer of the SV caller.
