### ISSUE TITLE
How to merge SV vcfs from different callers?

### ISSUE THREAD

**Issue by xiucz** [ACEnglish/truvari#106]
Hi ,

Thanks for your tool, and I try to test in my research.
I tried the `bench`  or `consistency` command to merge my SV vcfs from `Manta` and `svaba`. But I cannot get the merged result. Is there a function to do that ?

Best,
xiucz

**Comment by ACEnglish** [comment]
Hello,

The command you're looking for is [`truvari collapse`](https://github.com/ACEnglish/truvari/wiki/collapse). 
There isn't a lot of testing with VCFs produced by different callers. So you'll need to ensure the variants are a 'homogenous' as possible. For example, do the callers produce the same SVTYPE annotation for variants of the same SV types e.g. (some callers produce DUP/INS while others produce only INS. Ensure you're okay with this. I'd also want to make sure both callers have the REF/ALT sequences populated the same.

Feel free to reopen this ticket if you run into problems and I'll be happy to help you work through it.
