### ISSUE TITLE
pysam ValueError: start out of range (-1500)

### ISSUE THREAD

**Issue by rlorigro** [ACEnglish/truvari#107]
**Version** : 

Truvari v3.1.0 (latest on pip)

**Describe the bug** : 

Exits with the following stderr/stdout
```
2022-03-29 18:14:44,524 [INFO] Running /home/ubuntu/.local/bin/truvari bench --base /data/sv/samples/hg0073
3/hifiasm/variants.vcf.gz --comp /data/sv/samples/hg00733/hapdup/variants.vcf.gz --reference /data/sv/hg37/
human_g1k_v37.fasta -o /data/sv/samples/hg00733/hapdup/truvari --passonly -r 2000 -C 2000
2022-03-29 18:14:44,524 [INFO] Params:
{
    "base": "/data/sv/samples/hg00733/hifiasm/variants.vcf.gz",
    "comp": "/data/sv/samples/hg00733/hapdup/variants.vcf.gz",
    "output": "/data/sv/samples/hg00733/hapdup/truvari",
    "reference": "/data/sv/hg37/human_g1k_v37.fasta",
    "giabreport": false,
    "debug": false,
    "prog": false,
    "refdist": 2000,
    "pctsim": 0.7,
    "buffer": 0.1,
    "pctsize": 0.7,
    "pctovl": 0.0,
    "typeignore": false,
    "use_lev": false,
    "chunksize": 2000,
    "gtcomp": false,
    "bSample": null,
    "cSample": null,
    "sizemin": 50,
    "sizefilt": 30,
    "sizemax": 50000,
    "passonly": true,
    "no_ref": false,
    "includebed": null,
    "multimatch": false
}
2022-03-29 18:14:44,524 [INFO] Truvari version: 3.1.0
[W::bcf_update_info] INFO/END=0 is smaller than POS at 13:1
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/truvari", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/truvari/__main__.py", line 82, in main
    TOOLS[args.cmd](args.options) 
  File "/home/ubuntu/.local/lib/python3.8/site-packages/truvari/bench.py", line 775, in bench_main
    for call in itertools.chain.from_iterable(map(compare_chunk, chunks)):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/truvari/bench.py", line 398, in compare_chunk
    mat = matcher.build_match(b, c, f"{chunk_id}.{bid}.{cid}")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/truvari/bench.py", line 212, in build_match
    ret.seqsim = truvari.entry_pctsim(base, comp, self.params.reference,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/truvari/comparisons.py", line 257, in entry_pctsim
    allele1, allele2 = entry_create_haplotype(entryA, entryB, ref, buf_len=buf_len)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/truvari/comparisons.py", line 204, in entry_create_
haplotype
    return create_pos_haplotype(a1, a2, ref, buf_len=buf_len)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/truvari/comparisons.py", line 170, in create_pos_ha
plotype
    hap1_seq = ref.fetch(chrom, start, a1_start) + \
  File "pysam/libcfaidx.pyx", line 290, in pysam.libcfaidx.FastaFile.fetch
  File "pysam/libcutils.pyx", line 282, in pysam.libcutils.parse_region
ValueError: start out of range (-1500)
```

**Expected behavior** : 
No crash

**Example Data** : 
Willing to share if approved by @fenderglass

**Comment by ACEnglish** [comment]
Thanks for reporting this. I saw the potential for this error a while ago but failed to fix it. See the referenced commit for a fix. I plan on cutting a v3.2 soon, but until then you'll need to work off of develop [see wiki for details](https://github.com/ACEnglish/truvari/wiki/Installation).

Beyond the truvari error, you also have the line
```
[W::bcf_update_info] INFO/END=0 is smaller than POS at 13:1
```
This is thrown by pysam/htslib directly, and suggests there may be a problem with your VCF. My guess is you have a variant starting on chromosome 13 at position 1 with the INFO/END at 0. Having END < POS is invalid. Also, END == 0 suggests your VCF may have problems with 0-based vs 1-based indexing.

**Comment by rlorigro** [comment]
thanks for the quick fix. must be a new record for me, in terms of response rate.

**Comment by rlorigro** [comment]
> This is thrown by pysam/htslib directly, and suggests there may be a problem with your VCF. My guess is you have a variant starting on chromosome 13 at position 1 with the INFO/END at 0. Having END < POS is invalid. Also, END == 0 suggests your VCF may have problems with 0-based vs 1-based indexing.

I see. Thanks for the heads up. These VCFs are generated using another tool... I may have to open an issue with them.

**Comment by rlorigro** [comment]
@ACEnglish It looks like the install fails when I build from the dev branch. It ends on this message:

```
Installed /usr/local/lib/python3.8/dist-packages/sortedcontainers-2.4.0-py3.8.egg
error: setuptools 45.2.0 is installed but setuptools>=49.2.0 is required by {'bwapy'}
```

But it does seem to be running despite this error...

**Comment by ACEnglish** [comment]
bwapy is only required for a couple of the `truvari anno` commands. It's a kinda finicky package so I built it in a way that if its installation fails the rest of truvari still works. But if you wanted to fix it, I suspect you could simply do:
```bash
python3 -m pip install --upgrade setuptools
```
