### ISSUE TITLE
Running in KeyError with truvari collapse v3.1.0 while earlier v2.1.1 generates collapsed VCF

### ISSUE THREAD

**Issue by mdehankar3** [ACEnglish/truvari#109]
**Version** : v3.1.0

**Describe the bug** : I am using truvari v3.1.0 to generate a collapsed VCF after generating merge.vcf.gz consisting of SV calls from pbsv, sniffles and svim callers. v3.1.0 runs into following error due to one of pbsv's format terms SAC :

KeyError: 'invalid FORMAT: SAC'

while earlier truvari v2.1.1 is able to run through to completion and generate output.vcf and collapse.vcf files. Any pointers to get around this issue are very much appreciated!

**To Reproduce** : 
truvari collapse -i merge.vcf.gz -o output.vcf -c collapsed.vcf -f hg19.ref.fa -p 0 -P 0.70 -r 200 --chain --sizemin 1 --sizemax 10000000000

**Comment by ACEnglish** [comment]
This seems like an error with probably pbsv. The FORMAT/SAC is likely not defined correctly in the header. See [the wiki](https://github.com/ACEnglish/truvari/wiki#before-you-start) for information about how to check your input VCFs.
