### ISSUE TITLE
truvari anno trf duplicates variants

### ISSUE THREAD

**Issue by noorsmal** [ACEnglish/truvari#115]
**Version** : 

v3.2.0

**Describe the bug** : 

When I run truvari anno trf it duplicates certain variants. These are variants that cross 1 Mb borders (like a DEL at chr1:16999972 with SVLEN = -47).

**To Reproduce** : 

command: 
truvari anno trf -i example_input_insdel.vcf.gz -o example_output_insdel.vcf -f /complgen/refseq/hg38/genome_hg38.fa -t 1 -e trf -s ../annotfiles/grch38.simpleRepeat.truvari.bed.gz

output:
2022-04-27 13:00:46,665 [INFO] Running /home/noor/miniconda3/envs/sniffles2/bin/truvari anno trf -i example_input_insdel.vcf.gz -o example_output_insdel.vcf -f /complgen/refseq/hg38/genome_hg38.fa -t 1 -e trf -s ../annotfiles/grch38.simpleRepeat.truvari.bed.gz
2022-04-27 13:15:05,710 [INFO] Finished trf

**Expected behavior** : 
I expect it to create a compressed vcf file with all the original variants present and onduplicated, and novel information in the INFO column about tandem repeats. I get an uncompressed vcf (also when naming the output file output.vcf.gz) with some duplicated SV.

**Example Data** : 
see example_input_insdel.vcf.gz and example_output_insdel.vcf.gz (compressed with bgzip after running truvari)

**Additional context** :
Truvari was installed through conda 
[example_input_insdel.vcf.gz](https://github.com/ACEnglish/truvari/files/8571555/example_input_insdel.vcf.gz)
[example_output_insdel.vcf.gz](https://github.com/ACEnglish/truvari/files/8571564/example_output_insdel.vcf.gz)

**Comment by ACEnglish** [comment]
Thanks for reporting this. I thought I had fixed this in 3.2 but thanks to your ticket realized I did not. 

If you'd like a simple fix for any VCFs without having to re-run them from scratch. I found the following command helpful. 
```bash
gunzip -c input.vcf.gz | uniq | bgzip > output.vcf.gz
```

Note that you may want to double check just to be sure.
