### ISSUE TITLE
Clarification of the output (fp.vcf) and the FP field in the summary.txt 

### ISSUE THREAD

**Issue by miyakokodama** [ACEnglish/truvari#116]
Hi,

I am a new user of Truvari (thanks for the nice tool!), and have recently started comparing some vcfs to a truthset vcf using this tool and have a couple of questions. 

In particular, I am confused over the fp.vcf output (false positive calls from comparison) and the FP field in the summary.txt - here for this specific case, my fp.vcf file contains roughly 70 SVs, meaning that those 70SVs were not in the truthset (so, false positives...right?).

However, the FP field in the summary.txt shows 0 and I am thinking it should be 70? 

I must be missing something here so any feedback would be highly appreciated. Many thanks in advance!

Miyako

**Comment by ACEnglish** [comment]
Your expectations are correct. The VCFs should have as many entries as the counts in the summary.txt. For example, in our testing infrastructure, we see:

```bash
$ head summary.txt
{
    "TP-base": 7,
    "TP-call": 8,
    "FP": 9,
    "FN": 4,
    "precision": 0.47058823529411764,
    "recall": 0.6363636363636364,
    "f1": 0.5410628019323671,
    "base cnt": 11,
    "call cnt": 17,
$ grep -vc "#" *.vcf
fn.vcf:4
fp.vcf:9
tp-base.vcf:7
tp-call.vcf:8
```

If those two commands (head/grep) aren't matching up, I expect there's some sort of problem. Could you double check that those two commands aren't matching up and if not, provide example data so that I can recreate the problem.

**Comment by miyakokodama** [comment]
Hi! Thanks for your quick reply. That makes sense, I just checked as you suggested using head/grep and I now can't seem to recreate the problem - so I will close the issue for now :) Many thanks for your quick help!

**Comment by miyakokodama** [comment]
Hi! Thanks for your quick reply. That makes sense, I just checked as you suggested using head/grep and I now can't seem to recreate the problem - so I will close the issue for now :) Many thanks for your quick help!
