### ISSUE TITLE
Clarification needed over the summary.txt file

### ISSUE THREAD

**Issue by miyakokodama** [ACEnglish/truvari#118]
Hi! 

I have run Truvari on some of the vcf files (mainly outputs from Manda/Delly/Lumpy), and there are a couple of things I hope you can help me understand. 

I have a comparison vcf file that contains 53 deletions and 22 insertions (as Truvari benchmarks only del/ins, I have filtered out other types of SVs beforehand), and compared it to a truthset vcf using Truvari. The resulting file, summary.txt, indicates that there are 61 true positives detected in the comp vcf, and 9 false positives. I am confused by why these numbers (61+9) are not adding up to 75 (53+22 in the comp vcf). 

I do see in my comp vcf that some SVs are overlapping, and they may be considered as one SV by Truvari if there are high enough similarities among them? Are they any other things that may be causing the numbers not matching between base and comp vcfs? 

Any feedback would be highly appreciated - many thanks in advance :)
Miyako

**Comment by ACEnglish** [comment]
Are you using default parameters? If so, there are [size parameters](https://github.com/ACEnglish/truvari/wiki/bench#difference-between---sizemin-and---sizefilt) which may be removing SVs.

**Comment by miyakokodama** [comment]
Yes, I am using default parameters. Are you referring to the "pctsize" parameter?

**Comment by ACEnglish** [comment]
No, I'm referring to the size parameters https://github.com/ACEnglish/truvari/wiki/bench#difference-between---sizemin-and---sizefilt as described in the documentation
