### ISSUE TITLE
Invalid argument and BCF warning

### ISSUE THREAD

**Issue by paudano** [ACEnglish/truvari#123]
I am using Truvari to see how it compares two samples. It's failing with "Invalid argument", which may or may not be related to a BCF INFO tag "too large" warning. Details below.

**Version** : 
3.2.0

**Describe the bug** : 
Running "truvari bench" fails with...

```
[E::vcf_format] Invalid BCF, the INFO tag id=16 is too large at chr1:10828
Traceback (most recent call last):
  File "/pod/2/beck-lab/audanp/projects/2022_merge_strategies/tools/truvari/4.8.3/bin/truvari", line 33, in <module>
    sys.exit(load_entry_point('Truvari==3.2.0', 'console_scripts', 'truvari')())
  File "/pod/2/beck-lab/audanp/projects/2022_merge_strategies/tools/truvari/4.8.3/lib/python3.7/site-packages/truvari/__main__.py", line 85, in main
    TOOLS[args.cmd](args.options)
  File "/pod/2/beck-lab/audanp/projects/2022_merge_strategies/tools/truvari/4.8.3/lib/python3.7/site-packages/truvari/bench.py", line 797, in bench_main
    output_writer(call, outputs, args.sizemin)
  File "/pod/2/beck-lab/audanp/projects/2022_merge_strategies/tools/truvari/4.8.3/lib/python3.7/site-packages/truvari/bench.py", line 577, in output_writer
    outs["fp_out"].write(call.comp)
  File "pysam/libcbcf.pyx", line 4419, in pysam.libcbcf.VariantFile.write
  File "pysam/libcbcf.pyx", line 4456, in pysam.libcbcf.VariantFile.write
OSError: [Errno 22] b'Invalid argument'

```

**To Reproduce** : 
`truvari bench -b HG00733_sv_ins.vcf.gz -c HG00514_sv_ins.vcf.gz -f hg38.no_alt.fa.gz -o run_dir`

**Example Data** : 
If applicable/possible, add example data to help recreate your problem.

**Additional context** :
Deployed in a virtual environment.

```
python3 -m venv 4.8.3
. 4.8.3/bin/activate
4.8.3/bin/python3 -m pip install --upgrade pip
git clone --recursive git@github.com:ACEnglish/truvari.git -b v3.2.0
pushd truvari
pip3 install .
```

**Files**:
[HG00733_sv_ins.vcf.gz](https://github.com/ACEnglish/truvari/files/8734229/HG00733_sv_ins.vcf.gz)
[HG00514_sv_ins.vcf.gz](https://github.com/ACEnglish/truvari/files/8734230/HG00514_sv_ins.vcf.gz)

The reference (hg38 primary assembly only) can be found here:
ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/HGSVC2/technical/reference/20200513_hg38_NoALT/

**Comment by ACEnglish** [comment]
Hello,

The problem is the `INFO/SEQ` field. Some insertions seem to be too long for pysam/htslib to parse. Using `INFO/SEQ` is surprisingly common, but Truvari expects insertion sequences to be inside the ALT column, which - to me - seems like a more logical place for the sequence. Please try to alter your VCFs with the below script (note I made this fast, so it's provided  without warranty)

```python
import sys
import pysam

in_vcf = pysam.VariantFile(sys.argv[1])
out_vcf = pysam.VariantFile(sys.argv[2], 'w', header=in_vcf.header)

for entry in in_vcf:
    entry.alts = (entry.info["SEQ"])
    del(entry.info["SEQ"])
    out_vcf.write(entry)
```

**Comment by paudano** [comment]
No problem, the pipeline I'm using can write both full ALTs and symbolic alts. Works with the sequence in ALT, thanks!

For the code above, wouldn't you need to add the reference base to the ALT column to make the correct ALT? Mentioning it in case someone finds and uses it.

Thanks for the quick reply! It's working for me now.
