### ISSUE TITLE
Effects of case on indel comparison

### ISSUE THREAD

**Issue by mnshgl0110** [ACEnglish/truvari#128]
Hi,

I used truvari bench to compare two vcfs. An insertion that is present in both the vcfs is not called as TP.
```
(mgpy3.8) 18:01 goel@pc-t7-130 netscratch:test_truvari$ tail -1 fn.vcf 
NC_000001.11	50381601	.	T	TGTGAGGAGCCTCTCTGCCTGGCTGCCCAGTCTGGAAAGTGAGGAGCGTCTCTGCCCGGCCGCCATCCCATCTAGGAA	50	PASS	platforms=1;platformnames=PacBio;datasets=1;datasetnames=CCS15kb_20kb;callsets=1;callsetnames=CCS15kb_20kbDV;datasetsmissingcall=HiSeqPE300x,10XChromiumLR,CCS15kb_20kb,CGnormal,HiSeq250x250,HiSeqMatePair,IonExome,SolidSE75bp;callable=CS_CCS15kb_20kbDV_callable;filt=CS_HiSeqPE300xSentieon_filt,CS_10XLRGATK_filt,CS_HiSeqPE300xfreebayes_filt,CS_HiSeq250x250freebayes_filt,CS_HiSeqMatePairfreebayes_filt;difficultregion=GRCh38_AllTandemRepeats_201to10000bp_slop5,lowmappabilityall;PctSeqSimilarity=0.5;PctSizeSimilarity=1;PctRecOverlap=1;SizeDiff=0;StartDistance=0;EndDistance=0;TruScore=83;MatchId=2.0.0	GT:PS:DP:ADALL:AD:GQ	0/1:.:61:41,18:41,18:42
(mgpy3.8) 18:06 goel@pc-t7-130 netscratch:test_truvari$ tail -3 fp.vcf | head -1
NC_000001.11	50381601	INS61909	t	tgtgaggagcctctctgcctggctgcccagtctggaaagtgaggagcgtctctgcccggccgccatcccatctaggaa	.	PASS	ChrB=CM039011.1;StartB=50582675;EndB=50582752;Parent=SYN6;VarType=ShV;DupType=.;PctSeqSimilarity=0.5;PctSizeSimilarity=1;PctRecOverlap=1;SizeDiff=0;StartDistance=0;EndDistance=0;TruScore=83;MatchId=2.0.0	GT	.
```
The only reason I could think that can cause this is that truvari is case sensitive? Could you please confirm whether that is the case? As in vcf REF/ALT fields are case insensitive, I think it would be better if truvari is also case insensitive. In case there is any specific reason for this design choice, could you please share it?

Best
Manish

**Comment by ACEnglish** [comment]
When truvari was first developed, I believe [VCF v4.0](https://www.internationalgenome.org/wiki/Analysis/vcf4.0/) format specification was the latest in which it was specified that "Bases should be in uppercase".  Apparently that has changed in [newer versions](https://samtools.github.io/hts-specs/VCFv4.2.pdf) I'll put in a change.
