### ISSUE TITLE
Conda installation -- issue with header definitions when running truvari

### ISSUE THREAD

**Issue by tdelhomme** [ACEnglish/truvari#130]
**Version** : 

truvari conda last version:  v0.1.2018.08.10

**Describe the bug** : 

I tested truvari on same vcf for base and comparison, I get this error from the log file:
```
2022-07-26 16:10:52,652 [INFO] Running /home/tdelhomme/.conda/envs/truvari/bin/truvari -b PAM56393_1_0_sort.vcf.gz -c PAM56393_1_0_sort.vcf.gz -f /g/strcombio/fsupek_cancer3/own_genomes_tumors/from_CNAG/Osteosarcoma_project/ONT/Tumor/hg38.fa -o test_output_dir
2022-07-26 16:10:52,652 [INFO] Params:
{
    "pctovl": 0.0, 
    "sizemax": 50000, 
    "includebed": null, 
    "sizefilt": 30, 
    "cSample": null, 
    "reference": "/g/strcombio/fsupek_cancer3/own_genomes_tumors/from_CNAG/Osteosarcoma_project/ONT/Tumor/hg38.fa", 
    "no_ref": false, 
    "multimatch": false, 
    "comp": "PAM56393_1_0_sort.vcf.gz", 
    "typeignore": false, 
    "refdist": 500, 
    "pctsize": 0.7, 
    "passonly": false, 
    "base": "PAM56393_1_0_sort.vcf.gz", 
    "pctsim": 0.7, 
    "gtcomp": false, 
    "giabreport": false, 
    "debug": false, 
    "output": "test_output_dir", 
    "bSample": null, 
    "sizemin": 50
}
2022-07-26 16:10:52,709 [INFO] Creating call interval tree for overlap search
2022-07-26 16:10:53,189 [ERROR] Unable to parse comparison vcf file. Please check header definitions
2022-07-26 16:10:53,190 [ERROR] Specific error: "IntervalTree: Null Interval objects not allowed in IntervalTree: Interval(264856, 264856, 264856)"
```

**To Reproduce** : 

```
truvari -b PAM56393_1_0_sort.vcf.gz -c PAM56393_1_0_sort.vcf.gz -f hg38.fa -o test_output_dir
```

**Expected behavior** : 
Output folder as described in the documentation

**Example Data** : 

**Additional context** :
Maybe the conda is not updated because the `bench` command (and probably the others) is not available

**Comment by ACEnglish** [comment]
This is a very old version which I didn't even release onto conda. I'm unfamiliar with conda and had help getting the newer versions auto-deployed onto bioconda, so I'm not sure what's happening here.

But digging in a little bit, I can see that v3.4 is out there:
https://anaconda.org/bioconda/truvari

And it looks like the v0.1.* (which, again, I didn't make) is somehow considered the latest version? https://anaconda.org/bioconda/truvari/labels

Did you install off the main label instead of this old/unsupported one? e.g. `conda install -c bioconda truvari` and not `conda install -c bioconda/label/cf201901 truvari`?

**Comment by tdelhomme** [comment]
I used `conda install -c bioconda truvari`, would you suggest to install it not using conda?

**Comment by tdelhomme** [comment]
Installing into a conda environment using the latest version works correctly on the same files, I think the conda version is obselete. Could you mention it in the documentation for other users? thanks!
Here are the commands that can be used to create the environment:
```
# create and go inside the environment
conda create --name truvari python=3.9
conda activate truvari

# install last stable truvari and run a test
python3 -m pip install truvari
truvari -b PAM56393_1_0_sort.vcf.gz -c PAM56393_1_0_sort.vcf.gz -f hg38.fa -o test_output_dir

# go outside the environment 
conda deactivate truvary
```

**Comment by ACEnglish** [comment]
Thanks for following up on this. I've referenced your comment in updated documentation on the [wiki](https://github.com/ACEnglish/truvari/wiki/Installation#conda--mamba). When I get time, I'll try to figure out how to sort out the old release on conda.
