### ISSUE TITLE
A quick query about correlation 

### ISSUE THREAD

**Issue by tuannguyen8390** [ACEnglish/truvari#135]
Hi Truvari dev team,

Tried Truvari recently, very impressed with this piece of software 👍 💯 . Many thanks for this.

I was wondering if there is a way to calculate the correlation between the 2 vcfs (say, for example, Pearson correlation between the overlap variants). I understand there is an option to look at gt concordance, but as far as I know it is biased with allele frequency, while Pearson correlation isn't. 

Many thanks,

Tuan

**Comment by ACEnglish** [comment]
I don't think I fully understand the question. You can look at the percent of calls that intersect using `truvari bench`'s output report `summary.txt` which report precision and recall. These numbers are how percents of how many calls are contained in both VCFs. 
Could you please clarify what you're looking for?
