### ISSUE TITLE
query about VCF bed intersection

### ISSUE THREAD

**Issue by prasundutta87** [ACEnglish/truvari#138]
Hi,

I have been trying to impliment a basic method to filter my VCF based on a bed file or another VCF file. I am asking this query here because truvari works with comparing SVs in-between two VCF/bed file and mainly concentrates on INS and DEL. My aim is to find out SVs (INS, DEL, DUP, INV and TRA) that are common to my SV VCF and another BED file. I am aiming to have multiple BED/BEDPE files, each with a specific SV type so that I can use bedtools to easily intersect my VCF with bed and get what I want. Do you think this is the right way to go forward with this? How do I treat insertions as they will essentially have the same start and end position. Could you kindly point me to the truvari code where insertions are being compared? I wanted to know how svlen can be taken into account in bedtools in case I want to compare insertions.

Regards,
Prasun

**Comment by ACEnglish** [comment]
Variants are compared by `truvari.Matcher`.

**Comment by prasundutta87** [comment]
Thanks @ACEnglish !
