### ISSUE TITLE
TypeError: values expected to be 2-tuple, given len=1

### ISSUE THREAD

**Issue by tongyin121** [ACEnglish/truvari#157]
Hello, I get same issues when I use the truvari bench. Here are my issue report and the first 100 rows of my vcf file.
[truvari_bench.log](https://github.com/ACEnglish/truvari/files/11583537/truvari_bench.log)
[head100.vcf.gz](https://github.com/ACEnglish/truvari/files/11583542/head100.vcf.gz)
By the way, I also have tried the usable_vcf.py on my vcf file. However, I still don't know where the specific issue with my vcf file.
[usable_vcf.log](https://github.com/ACEnglish/truvari/files/11583552/usable_vcf.log)
Do you know what this may be due to ?
Thank you, regards.

**Comment by ACEnglish** [comment]
Looks like you're using an older version (Looks like v3.0, maybe). Could you try updating to a newer version first?

**Comment by tongyin121** [comment]
It works, thank you.
