### ISSUE TITLE
Are "TP-base" and "TP-comp" always the same value?

### ISSUE THREAD

**Issue by Samvkes** [ACEnglish/truvari#159]
The summary.json files out of bench include the values 'TP-base' and 'TP-comp' near the top. These are the amount of matches between the 2 sets found in each set. 

I understand why these are the same: a match is by definition found in both sets, but why include both values if they are always going to be the same anyway?

**Comment by ACEnglish** [comment]
With default parameters, they are always the same. However, altering the [--pick](https://github.com/ACEnglish/truvari/wiki/bench#controlling-the-number-of-matches) parameter can cause tp-base/tp-comp valuse to differ.
