### ISSUE TITLE
The SVLEN and -m flag have somewhat unexpected behavior when REF and ALT are both long

### ISSUE THREAD

**Issue by rickymagner** [ACEnglish/truvari#162]
**Version** : 

`Truvari v4.0.0`

**Describe the bug** : 

The command `truvari anno svinfo` does not work with the `-m` flag in the way expected. In particular, `truvari anno svinfo -m` does not take into account the relative difference in sizes between the `REF` and `ALT` sequences. In particular, if your SV caller outputs long sequences for both (which I've seen a few times), you may end up including events whose size should be below the `-m` value get included anyway. This is probably due to the `SVLEN` attribute getting computed improperly in this case as well.

**To Reproduce** : 

Here's an example variant I ran `truvari anno svinfo -m 50` on:
```
chr1    811390  .       AATACAATGTTCTCCAGAAATAGTGTCGCAGAAATAAAGACAGAATATGGAAGGAGACAGGATTGCTGACTAATCTCATATGTACAGGGAGAACGACACTCCATGCAGCTTAGCTCCAACATGTGAGCGTGGGACAGAAAAGCAAGGTGAACCTAAAGACATCCCATGGACACACTGAGCTGGAACCAACTCTGCCCATAGGTGGTGGGGCCAGGTTCAGATGCTTGCAGTAACCGCATCCTCCTGTGAATCTGGGTCTACATGGCTGTGGCTCCCTGGGGGCTACCCACACTGTGGATTCCACAGGTGGAGGTGACCTTCTTGGGCACTGCTGGGACACTTCCTGGGCCTGCCTGGGCAGTGGTAGGGCTCAGAGAACTTCAGCGTTAGGGCCTTGGGGAGTCTATGTCAGACTTGAGGAC        AATACAATGTTCTCCAGAAATAGTGTCGCAGAAATAAAGACAGAATATGGAAGGAGACAGGATTGCTGACTAATCTCATATGTACAGGGAGAACGACACTCCATGCAGCTTAGCTCCAACATGTGAGTGTGGGACAGAAAAGCAAGGTGAACCTAAAGACATCCCATGGACACACTGAGCTGGAACCAACTCTGCCCATAGGTGGTGGGGCCAGGTTCAGATGCTTGCAGTAACCGCATCCTCCTGTGAATCTGGGTCTACATGGCTGTGGCTCCCTGGGGGCTACCCACACTGTGGATTCCACAGGTGGAGGTGACCTTCTTGGGCACTGCTGGGACACTTCTTGGGCCTGCCTGGGCAGTGGTAGGGCTCAGAGAACTTCAGCGTTAGGGCCTTGGGGAGTCTATGTCAGACTTGAGGAC        .       .       RAF=0.0322581;AF=0;INFO=1;BUF=0 GT:DS:GP:HS     0/0:0:1,0,0:0
```
The result is:
```
chr1    811390  .       AATACAATGTTCTCCAGAAATAGTGTCGCAGAAATAAAGACAGAATATGGAAGGAGACAGGATTGCTGACTAATCTCATATGTACAGGGAGAACGACACTCCATGCAGCTTAGCTCCAACATGTGAGCGTGGGACAGAAAAGCAAGGTGAACCTAAAGACATCCCATGGACACACTGAGCTGGAACCAACTCTGCCCATAGGTGGTGGGGCCAGGTTCAGATGCTTGCAGTAACCGCATCCTCCTGTGAATCTGGGTCTACATGGCTGTGGCTCCCTGGGGGCTACCCACACTGTGGATTCCACAGGTGGAGGTGACCTTCTTGGGCACTGCTGGGACACTTCCTGGGCCTGCCTGGGCAGTGGTAGGGCTCAGAGAACTTCAGCGTTAGGGCCTTGGGGAGTCTATGTCAGACTTGAGGAC        AATACAATGTTCTCCAGAAATAGTGTCGCAGAAATAAAGACAGAATATGGAAGGAGACAGGATTGCTGACTAATCTCATATGTACAGGGAGAACGACACTCCATGCAGCTTAGCTCCAACATGTGAGTGTGGGACAGAAAAGCAAGGTGAACCTAAAGACATCCCATGGACACACTGAGCTGGAACCAACTCTGCCCATAGGTGGTGGGGCCAGGTTCAGATGCTTGCAGTAACCGCATCCTCCTGTGAATCTGGGTCTACATGGCTGTGGCTCCCTGGGGGCTACCCACACTGTGGATTCCACAGGTGGAGGTGACCTTCTTGGGCACTGCTGGGACACTTCTTGGGCCTGCCTGGGCAGTGGTAGGGCTCAGAGAACTTCAGCGTTAGGGCCTTGGGGAGTCTATGTCAGACTTGAGGAC        .       .       RAF=0.0322581;AF=0;INFO=1;BUF=0;SVTYPE=UNK;SVLEN=422          GT:DS:GP:HS     0/0:0:1,0,0:0
```
Note that `SVLEN` ends up being the length of (both) sequences, even though the difference in length is 0. 

**Expected behavior** : 
The sequences themselves only differ by 2 SNPs, so it's unclear what the desired behavior should be. I thought this sort of site would've been filtered out when using `-m 50`. 

**Additional context** :
This might be a bit niche, but I've seen outputs like the above in a few different cases, where SNPs end up hiding in very long sequences. It might be worth considering if you want to compute `SVLEN` instead using something like the difference between the `REF` and `ALT` length.

**Comment by ACEnglish** [comment]
Hello,

SVLEN calculation can get weird. And while I do believe there are cases where `anno svinfo` may not annotate correctly, I'm unsure if this is one of them. Looking at the vcf4.4 spec ([link](https://github.com/samtools/hts-specs/blob/master/VCFv4.4.pdf)), the main definition of SVLEN is:
```
##INFO=<ID=SVLEN,Number=A,Type=Integer,Description="Length of structural variant">
One value for each ALT allele.
SVLEN must be specified for symbolic structural variant alleles. SVLEN is defined for INS, DUP, INV, and DEL symbolic alleles as the number of the inserted, duplicated, inverted, and deleted bases respectively. SVLEN is defined for CNV symbolic alleles as the length of the segment over which the copy number variant is defined. The missing value . should be used for all other ALT alleles, including ALT alleles using breakend notation.
For backwards compatibility, a missing SVLEN should be inferred from the END field of VCF records whose ALT field contains a single symbolic allele.
For backwards compatibility, the absolute value of SVLEN should be taken and a negative SVLEN should be treated as positive values.
Note that for structural variant symbolic alleles, P OS corresponds to the base immediately preceding the variant.
```

Which could(?) be interpreted as SVLEN should only be available for symbolic ALTs. However your example VCF line has a sequence resolved call. There's also this interesting - though possibly not-relevant - description of `rlen` in the bcf2 section which says:
```
rlen -> int32.t -> Length of the record as projected onto the reference sequence. Must be the maximum of the length of the REF allele and the lengths inferred from the SVLEN/END of any symbolic alleles
```

You can see the full description of how truvari calculates svlen [here](https://truvari.readthedocs.io/en/v4.0.0/truvari.html#truvari.entry_size).

One thought experiment that makes it tricky to know exactly how to handle this situation of SNPs in a span (which I like to think of unofficially as replacement or 'REPL' types) is to consider sequence resolved inversions. If an inversion is a perfect flip of a reference span, we'd probably want to set SVLEN to the reference span. Therefore, for truvari to understand if its looking at an inversion vs a 'REPL', it's need to incorporate reverse-compliment REF to ALT similarity and essentially become a sequence annotator. Also, the `anno svinfo` attempts to add the `INFO/SVTYPE` field,  and is very simplistic ([docs](https://truvari.readthedocs.io/en/v4.0.0/truvari.html#entry-variant-type)). However, I believe SVTYPE is being 'deprecated' from the VCF format specification - which I don't understand. 

To sum all of that up - I understand your logic for wanting to consider the example site as a 0-length "REPL" type. But I don't believe there's a way to handle it that way that without having the `anno svinfo` tool become more complicated in a way that may not conform to the ever-changing VCF specs. 

And, just to make sure, you say "I thought this sort of site would've been filtered out..". But the `anno svinfo` won't do any filtering. It just adds INFO fields. 

Have a great day,
~/Adam English

**Comment by rickymagner** [comment]
Thanks for your response and clarification!
