### ISSUE TITLE
Truvari refine hangs indefinitely

### ISSUE THREAD

**Issue by andy941** [ACEnglish/truvari#167]
**Version** : 

Truvari v4.1.1.dev0+f34071a

**Describe the bug** : 

Truvari refine hangs indefinitely:

```
# Runs OK
truvari bench -b ./GIABTR_benchmark.6.26/GIABTR.HG002.benchmark.vcf.gz -c ./input.vcf.gz --includebed ./GIABTR_benchmark.6.26/GIABTR.HG002.benchmark.regions.bed.gz --sizemin 5 --pick ac -o truvari/

# Hangs
truvari refine --debug -t 48 --use-original-vcfs --reference /illumina-isi07/sync/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa --regions ./variant_catalog.bed truvari

# refine output
2023-08-30 02:36:10,623 [INFO] Truvari v4.1.1.dev0+f34071a
2023-08-30 02:36:10,623 [INFO] Command /home/afinocchio/miniconda3/envs/biotools/bin/truvari refine --debug -t 48 --use-original-vcfs --reference genome.fa --regions ./variant_catalog.bed truvari/
2023-08-30 02:36:10,623 [INFO] Params:
{
    "benchdir": "truvari/",
    "reference": "genome.fa",
    "regions": "./variant_catalog.bed",
    "use_original_vcfs": true,
    "use_region_coords": false,
    "recount": false,
    "threads": 48,
    "align": "mafft",
    "debug": true
}
2023-08-30 02:36:10,623 [INFO] Setting up regions
2023-08-30 02:36:55,884 [INFO] 1706853 --includebed reduced to 45499 after intersecting with 50069 from --regions
2023-08-30 02:37:01,214 [INFO] 28432 regions to be refined
2023-08-30 02:37:01,319 [INFO] Preparing regions
2023-08-30 02:37:02,105 [INFO] Extracting haplotypes
/home/afinocchio/miniconda3/envs/biotools/bin/python3: /home/afinocchio/miniconda3/envs/biotools/bin/python3:
```
Notice the last two line printed, not sure why that happens (it's part of truvari refine output). After those it get stuck forever (I let it run overnight, no luck).

I tried to trace debug and it seems to be stuck searching an interval tree (this is just a bit of the trace output):

<details>
  <summary>Traceback</summary>
f.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(142):         if abs(self.balance) < 2:
node.py(143):             return self
 --- modulename: node, funcname: __setitem__
node.py(517):         if key:
node.py(520):             self.left_node = value
node.py(220):                 return self.rotate()
 --- modulename: node, funcname: rotate
node.py(141):         self.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(142):         if abs(self.balance) < 2:
node.py(143):             return self
intervaltree.py(333):         self.all_intervals.add(interval)
 --- modulename: interval, funcname: __hash__
interval.py(157):         return hash((self.begin, self.end))
intervaltree.py(334):         self._add_boundaries(interval)
 --- modulename: intervaltree, funcname: _add_boundaries
intervaltree.py(286):         begin = interval.begin
intervaltree.py(287):         end = interval.end
intervaltree.py(288):         if begin in self.boundary_table:
intervaltree.py(291):             self.boundary_table[begin] = 1
 --- modulename: sorteddict, funcname: __setitem__
sorteddict.py(298):         if key not in self:
sorteddict.py(299):             self._list_add(key)
 --- modulename: sortedlist, funcname: add
sortedlist.py(268):         _lists = self._lists
sortedlist.py(269):         _maxes = self._maxes
sortedlist.py(271):         if _maxes:
sortedlist.py(272):             pos = bisect_right(_maxes, value)
sortedlist.py(274):             if pos == len(_maxes):
sortedlist.py(279):                 insort(_lists[pos], value)
sortedlist.py(281):             self._expand(pos)
 --- modulename: sortedlist, funcname: _expand
sortedlist.py(298):         _load = self._load
sortedlist.py(299):         _lists = self._lists
sortedlist.py(300):         _index = self._index
sortedlist.py(302):         if len(_lists[pos]) > (_load << 1):
sortedlist.py(315):             if _index:
sortedlist.py(286):         self._len += 1
sorteddict.py(300):         dict.__setitem__(self, key, value)
intervaltree.py(293):         if end in self.boundary_table:
intervaltree.py(296):             self.boundary_table[end] = 1
 --- modulename: sorteddict, funcname: __setitem__
sorteddict.py(298):         if key not in self:
sorteddict.py(299):             self._list_add(key)
 --- modulename: sortedlist, funcname: add
sortedlist.py(268):         _lists = self._lists
sortedlist.py(269):         _maxes = self._maxes
sortedlist.py(271):         if _maxes:
sortedlist.py(272):             pos = bisect_right(_maxes, value)
sortedlist.py(274):             if pos == len(_maxes):
sortedlist.py(279):                 insort(_lists[pos], value)
sortedlist.py(281):             self._expand(pos)
 --- modulename: sortedlist, funcname: _expand
sortedlist.py(298):         _load = self._load
sortedlist.py(299):         _lists = self._lists
sortedlist.py(300):         _index = self._index
sortedlist.py(302):         if len(_lists[pos]) > (_load << 1):
sortedlist.py(315):             if _index:
sortedlist.py(286):         self._len += 1
sorteddict.py(300):         dict.__setitem__(self, key, value)
region_vcf_iter.py(166):         idx += 1
region_vcf_iter.py(154):     for line in truvari.opt_gz_open(filename):
 --- modulename: utils, funcname: fh_hdlr
utils.py(339):             for line in fh:
utils.py(340):                 yield line
region_vcf_iter.py(155):         if line.startswith(comment):
region_vcf_iter.py(157):         data = line.strip().split('\t')
region_vcf_iter.py(158):         chrom = data[chrom_col]
region_vcf_iter.py(159):         start = int(data[start_col]) - correction
region_vcf_iter.py(160):         end = int(data[end_col])
region_vcf_iter.py(161):         if idxfmt is not None:
region_vcf_iter.py(162):             m_idx = idxfmt.format(idx)
region_vcf_iter.py(165):         tree[chrom].addi(start, end + 1, data=m_idx)
 --- modulename: intervaltree, funcname: addi
intervaltree.py(343):         return self.add(Interval(begin, end, data))
 --- modulename: interval, funcname: __new__
interval.py(34):         return super(Interval, cls).__new__(cls, begin, end, data)
 --- modulename: intervaltree, funcname: add
intervaltree.py(320):         if interval in self:
 --- modulename: intervaltree, funcname: __contains__
intervaltree.py(1080):         return item in self.all_intervals
 --- modulename: interval, funcname: __hash__
interval.py(157):         return hash((self.begin, self.end))
intervaltree.py(323):         if interval.is_null():
 --- modulename: interval, funcname: is_null
interval.py(139):         return self.begin >= self.end
intervaltree.py(329):         if not self.top_node:
intervaltree.py(332):             self.top_node = self.top_node.add(interval)
 --- modulename: node, funcname: add
node.py(209):         if self.center_hit(interval):
 --- modulename: node, funcname: center_hit
node.py(108):         return interval.contains_point(self.x_center)
 --- modulename: interval, funcname: contains_point
interval.py(86):         return self.begin <= p < self.end
node.py(213):             direction = self.hit_branch(interval)
 --- modulename: node, funcname: hit_branch
node.py(115):         return interval.begin > self.x_center
node.py(214):             if not self[direction]:
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(513):             return self.left_node
node.py(219):                 self[direction] = self[direction].add(interval)
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(513):             return self.left_node
 --- modulename: node, funcname: add
node.py(209):         if self.center_hit(interval):
 --- modulename: node, funcname: center_hit
node.py(108):         return interval.contains_point(self.x_center)
 --- modulename: interval, funcname: contains_point
interval.py(86):         return self.begin <= p < self.end
node.py(213):             direction = self.hit_branch(interval)
 --- modulename: node, funcname: hit_branch
node.py(115):         return interval.begin > self.x_center
node.py(214):             if not self[direction]:
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
node.py(219):                 self[direction] = self[direction].add(interval)
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
 --- modulename: node, funcname: add
node.py(209):         if self.center_hit(interval):
 --- modulename: node, funcname: center_hit
node.py(108):         return interval.contains_point(self.x_center)
 --- modulename: interval, funcname: contains_point
interval.py(86):         return self.begin <= p < self.end
node.py(213):             direction = self.hit_branch(interval)
 --- modulename: node, funcname: hit_branch
node.py(115):         return interval.begin > self.x_center
node.py(214):             if not self[direction]:
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
node.py(219):                 self[direction] = self[direction].add(interval)
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
 --- modulename: node, funcname: add
node.py(209):         if self.center_hit(interval):
 --- modulename: node, funcname: center_hit
node.py(108):         return interval.contains_point(self.x_center)
 --- modulename: interval, funcname: contains_point
interval.py(86):         return self.begin <= p < self.end
node.py(213):             direction = self.hit_branch(interval)
 --- modulename: node, funcname: hit_branch
node.py(115):         return interval.begin > self.x_center
node.py(214):             if not self[direction]:
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(513):             return self.left_node
node.py(219):                 self[direction] = self[direction].add(interval)
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(513):             return self.left_node
 --- modulename: node, funcname: add
node.py(209):         if self.center_hit(interval):
 --- modulename: node, funcname: center_hit
node.py(108):         return interval.contains_point(self.x_center)
 --- modulename: interval, funcname: contains_point
interval.py(86):         return self.begin <= p < self.end
node.py(213):             direction = self.hit_branch(interval)
 --- modulename: node, funcname: hit_branch
node.py(115):         return interval.begin > self.x_center
node.py(214):             if not self[direction]:
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
node.py(219):                 self[direction] = self[direction].add(interval)
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
 --- modulename: node, funcname: add
node.py(209):         if self.center_hit(interval):
 --- modulename: node, funcname: center_hit
node.py(108):         return interval.contains_point(self.x_center)
 --- modulename: interval, funcname: contains_point
interval.py(86):         return self.begin <= p < self.end
node.py(213):             direction = self.hit_branch(interval)
 --- modulename: node, funcname: hit_branch
node.py(115):         return interval.begin > self.x_center
node.py(214):             if not self[direction]:
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
node.py(219):                 self[direction] = self[direction].add(interval)
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
 --- modulename: node, funcname: add
node.py(209):         if self.center_hit(interval):
 --- modulename: node, funcname: center_hit
node.py(108):         return interval.contains_point(self.x_center)
 --- modulename: interval, funcname: contains_point
interval.py(86):         return self.begin <= p < self.end
node.py(213):             direction = self.hit_branch(interval)
 --- modulename: node, funcname: hit_branch
node.py(115):         return interval.begin > self.x_center
node.py(214):             if not self[direction]:
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
node.py(219):                 self[direction] = self[direction].add(interval)
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
 --- modulename: node, funcname: add
node.py(209):         if self.center_hit(interval):
 --- modulename: node, funcname: center_hit
node.py(108):         return interval.contains_point(self.x_center)
 --- modulename: interval, funcname: contains_point
interval.py(86):         return self.begin <= p < self.end
node.py(213):             direction = self.hit_branch(interval)
 --- modulename: node, funcname: hit_branch
node.py(115):         return interval.begin > self.x_center
node.py(214):             if not self[direction]:
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
node.py(219):                 self[direction] = self[direction].add(interval)
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
 --- modulename: node, funcname: add
node.py(209):         if self.center_hit(interval):
 --- modulename: node, funcname: center_hit
node.py(108):         return interval.contains_point(self.x_center)
 --- modulename: interval, funcname: contains_point
interval.py(86):         return self.begin <= p < self.end
node.py(213):             direction = self.hit_branch(interval)
 --- modulename: node, funcname: hit_branch
node.py(115):         return interval.begin > self.x_center
node.py(214):             if not self[direction]:
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
node.py(219):                 self[direction] = self[direction].add(interval)
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
 --- modulename: node, funcname: add
node.py(209):         if self.center_hit(interval):
 --- modulename: node, funcname: center_hit
node.py(108):         return interval.contains_point(self.x_center)
 --- modulename: interval, funcname: contains_point
interval.py(86):         return self.begin <= p < self.end
node.py(213):             direction = self.hit_branch(interval)
 --- modulename: node, funcname: hit_branch
node.py(115):         return interval.begin > self.x_center
node.py(214):             if not self[direction]:
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
node.py(219):                 self[direction] = self[direction].add(interval)
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
 --- modulename: node, funcname: add
node.py(209):         if self.center_hit(interval):
 --- modulename: node, funcname: center_hit
node.py(108):         return interval.contains_point(self.x_center)
 --- modulename: interval, funcname: contains_point
interval.py(86):         return self.begin <= p < self.end
node.py(213):             direction = self.hit_branch(interval)
 --- modulename: node, funcname: hit_branch
node.py(115):         return interval.begin > self.x_center
node.py(214):             if not self[direction]:
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
node.py(219):                 self[direction] = self[direction].add(interval)
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
 --- modulename: node, funcname: add
node.py(209):         if self.center_hit(interval):
 --- modulename: node, funcname: center_hit
node.py(108):         return interval.contains_point(self.x_center)
 --- modulename: interval, funcname: contains_point
interval.py(86):         return self.begin <= p < self.end
node.py(213):             direction = self.hit_branch(interval)
 --- modulename: node, funcname: hit_branch
node.py(115):         return interval.begin > self.x_center
node.py(214):             if not self[direction]:
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
node.py(219):                 self[direction] = self[direction].add(interval)
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
 --- modulename: node, funcname: add
node.py(209):         if self.center_hit(interval):
 --- modulename: node, funcname: center_hit
node.py(108):         return interval.contains_point(self.x_center)
 --- modulename: interval, funcname: contains_point
interval.py(86):         return self.begin <= p < self.end
node.py(213):             direction = self.hit_branch(interval)
 --- modulename: node, funcname: hit_branch
node.py(115):         return interval.begin > self.x_center
node.py(214):             if not self[direction]:
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
node.py(215):                 self[direction] = Node.from_interval(interval)
 --- modulename: node, funcname: from_interval
node.py(64):         center = interval.begin
node.py(65):         return Node(center, [interval])
 --- modulename: node, funcname: __init__
node.py(51):         self.x_center = x_center
node.py(52):         self.s_center = set(s_center)
 --- modulename: interval, funcname: __hash__
interval.py(157):         return hash((self.begin, self.end))
node.py(53):         self.left_node = left_node
node.py(54):         self.right_node = right_node
node.py(55):         self.depth = 0    # will be set when rotated
node.py(56):         self.balance = 0  # ditto
node.py(57):         self.rotate()
 --- modulename: node, funcname: rotate
node.py(141):         self.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(142):         if abs(self.balance) < 2:
node.py(143):             return self
 --- modulename: node, funcname: __setitem__
node.py(517):         if key:
node.py(518):             self.right_node = value
node.py(216):                 self.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(217):                 return self
 --- modulename: node, funcname: __setitem__
node.py(517):         if key:
node.py(518):             self.right_node = value
node.py(220):                 return self.rotate()
 --- modulename: node, funcname: rotate
node.py(141):         self.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(142):         if abs(self.balance) < 2:
node.py(145):         my_heavy = self.balance > 0
node.py(146):         child_heavy = self[my_heavy].balance > 0
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
node.py(147):         if my_heavy == child_heavy or self[my_heavy].balance == 0:
node.py(157):             return self.srotate()
 --- modulename: node, funcname: srotate
node.py(172):         heavy = self.balance > 0
node.py(173):         light = not heavy
node.py(174):         save = self[heavy]
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(511):             return self.right_node
node.py(177):         self[heavy] = save[light]   # 2
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(513):             return self.left_node
 --- modulename: node, funcname: __setitem__
node.py(517):         if key:
node.py(518):             self.right_node = value
node.py(179):         save[light] = self.rotate()  # Needed to ensure the 2 and 3 are balanced under new subnode
 --- modulename: node, funcname: rotate
node.py(141):         self.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(142):         if abs(self.balance) < 2:
node.py(143):             return self
 --- modulename: node, funcname: __setitem__
node.py(517):         if key:
node.py(520):             self.left_node = value
node.py(183):         promotees = [iv for iv in save[light].s_center if save.center_hit(iv)]
 --- modulename: node, funcname: __getitem__
node.py(510):         if index:
node.py(513):             return self.left_node
 --- modulename: node, funcname: <listcomp>
node.py(183):         promotees = [iv for iv in save[light].s_center if save.center_hit(iv)]
 --- modulename: node, funcname: center_hit
node.py(108):         return interval.contains_point(self.x_center)
 --- modulename: interval, funcname: contains_point
interval.py(86):         return self.begin <= p < self.end
node.py(183):         promotees = [iv for iv in save[light].s_center if save.center_hit(iv)]
node.py(184):         if promotees:
node.py(191):         save.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(192):         return save
 --- modulename: node, funcname: __setitem__
node.py(517):         if key:
node.py(518):             self.right_node = value
node.py(220):                 return self.rotate()
 --- modulename: node, funcname: rotate
node.py(141):         self.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(142):         if abs(self.balance) < 2:
node.py(143):             return self
 --- modulename: node, funcname: __setitem__
node.py(517):         if key:
node.py(518):             self.right_node = value
node.py(220):                 return self.rotate()
 --- modulename: node, funcname: rotate
node.py(141):         self.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(142):         if abs(self.balance) < 2:
node.py(143):             return self
 --- modulename: node, funcname: __setitem__
node.py(517):         if key:
node.py(518):             self.right_node = value
node.py(220):                 return self.rotate()
 --- modulename: node, funcname: rotate
node.py(141):         self.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(142):         if abs(self.balance) < 2:
node.py(143):             return self
 --- modulename: node, funcname: __setitem__
node.py(517):         if key:
node.py(518):             self.right_node = value
node.py(220):                 return self.rotate()
 --- modulename: node, funcname: rotate
node.py(141):         self.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(142):         if abs(self.balance) < 2:
node.py(143):             return self
 --- modulename: node, funcname: __setitem__
node.py(517):         if key:
node.py(518):             self.right_node = value
node.py(220):                 return self.rotate()
 --- modulename: node, funcname: rotate
node.py(141):         self.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(142):         if abs(self.balance) < 2:
node.py(143):             return self
 --- modulename: node, funcname: __setitem__
node.py(517):         if key:
node.py(518):             self.right_node = value
node.py(220):                 return self.rotate()
 --- modulename: node, funcname: rotate
node.py(141):         self.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(142):         if abs(self.balance) < 2:
node.py(143):             return self
 --- modulename: node, funcname: __setitem__
node.py(517):         if key:
node.py(518):             self.right_node = value
node.py(220):                 return self.rotate()
 --- modulename: node, funcname: rotate
node.py(141):         self.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(142):         if abs(self.balance) < 2:
node.py(143):             return self
 --- modulename: node, funcname: __setitem__
node.py(517):         if key:
node.py(520):             self.left_node = value
node.py(220):                 return self.rotate()
 --- modulename: node, funcname: rotate
node.py(141):         self.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(142):         if abs(self.balance) < 2:
node.py(143):             return self
 --- modulename: node, funcname: __setitem__
node.py(517):         if key:
node.py(518):             self.right_node = value
node.py(220):                 return self.rotate()
 --- modulename: node, funcname: rotate
node.py(141):         self.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(142):         if abs(self.balance) < 2:
node.py(143):             return self
 --- modulename: node, funcname: __setitem__
node.py(517):         if key:
node.py(518):             self.right_node = value
node.py(220):                 return self.rotate()
 --- modulename: node, funcname: rotate
node.py(141):         self.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(142):         if abs(self.balance) < 2:
node.py(143):             return self
 --- modulename: node, funcname: __setitem__
node.py(517):         if key:
node.py(520):             self.left_node = value
node.py(220):                 return self.rotate()
 --- modulename: node, funcname: rotate
node.py(141):         self.refresh_balance()
 --- modulename: node, funcname: refresh_balance
node.py(121):         left_depth = self.left_node.depth if self.left_node else 0
node.py(122):         right_depth = self.right_node.depth if self.right_node else 0
node.py(123):         self.depth = 1 + max(left_depth, right_depth)
node.py(124):         self.balance = right_depth - left_depth
node.py(142):         if abs(self.balance) < 2:
node.py(143):             return self
intervaltree.py(333):         self.all_intervals.add(interval)
 --- modulename: interval, funcname: __hash__
interval.py(157):         return hash((self.begin, self.end))
intervaltree.py(334):         self._add_boundaries(interval)
 --- modulename: intervaltree, funcname: _add_boundaries
intervaltree.py(286):         begin = interval.begin
intervaltree.py(287):         end = interval.end
intervaltree.py(288):         if begin in self.boundary_table:
intervaltree.py(291):             self.boundary_table[begin] = 1
 --- modulename: sorteddict, funcname: __setitem__
sorteddict.py(298):         if key not in self:
sorteddict.py(299):             self._list_add(key)
 --- modulename: sortedlist, funcname: add
sortedlist.py(268):         _lists = self._lists
sortedlist.py(269):         _maxes = self._maxes
sortedlist.py(271):         if _maxes:
sortedlist.py(272):             pos = bisect_right(_maxes, value)
sortedlist.py(274):             if pos == len(_maxes):
sortedlist.py(279):                 insort(_lists[pos], value)
sortedlist.py(281):             self._expand(pos)
 --- modulename: sortedlist, funcname: _expand
sortedlist.py(298):         _load = self._load
sortedlist.py(299):         _lists = self._lists
sortedlist.py(300):         _index = self._index
sortedlist.py(302):         if len(_lists[pos]) > (_load << 1):
sortedlist.py(315):             if _index:
sortedlist.py(286):         self._len += 1
sorteddict.py(300):         dict.__setitem__(self, key, value)
intervaltree.py(293):         if end in self.boundary_table:
intervaltree.py(296):             self.boundary_table[end] = 1
 --- modulename: sorteddict, funcname: __setitem__
sorteddict.py(298):         if key not in self:
sorteddict.py(299):             self._list_add(key)
 --- modulename: sortedlist, funcname: add
sortedlist.py(268):         _lists = self._lists
sortedlist.py(269):         _maxes = self._maxes
sortedlist.py(271):         if _maxes:
sortedlist.py(272):             pos = bisect_right(_maxes, value)
sortedlist.py(274):             if pos == len(_maxes):
sortedlist.py(279):                 insort(_lists[pos], value)
sortedlist.py(281):             self._expand(pos)
 --- modulename: sortedlist, funcname: _expand
sortedlist.py(298):         _load = self._load
sortedlist.py(299):         _lists = self._lists
sortedlist.py(300):         _index = self._index
sortedlist.py(302):         if len(_lists[pos]) > (_load << 1):
sortedlist.py(315):             if _index:
sortedlist.py(286):         self._len += 1
sorteddict.py(300):         dict.__setitem__(self, key, value)
region_vcf_iter.py(166):         idx += 1
region_vcf_iter.py(154):     for line in truvari.opt_gz_open(filename):
 --- modulename: utils, funcname: fh_hdlr
utils.py(339):             for line in fh:
utils.py(340):                 yield line
region_vcf_iter.py(155):         if line.startswith(comment):
region_vcf_iter.py(157):         data = line.strip().split('\t')
region_vcf_iter.py(158):         chrom = data[chrom_col]
region_vcf_iter.py(159):         start = int(data[start_col]) - correction
region_vcf_iter.py(160):         end = int(data[end_col])
region_vcf_iter.py(161):         if idxfmt is not None:
region_vcf_iter.py(162):             m_idx = idxfmt.format(idx)
region_vcf_iter.py(165):         tree[chrom].addi(start, end + 1, data=m_idx)
</details>

**To Reproduce** : 

**Expected behavior** : 
Run to completion

**Example Data** : 

**Additional context** :
I am trying to follow the steps described in the  GIABTR6.26 benchmark.

**Comment by ACEnglish** [comment]
Hello,

The traceback lines are made somewhere around `truvari.region_vcf_iter:build_anno_tree` which is called in `truvari.refine.resolve_regions`, which is run between refine's `logging.info("Params:...` and `logging.info("%d regions to be refined"`.  

So the traceback is stuff that happens during the first half of the setup before the variants/regions are sent to be harmonized. You're hanging during `truvari.phab`.

If I had to guess, you're hanging somewhere around the call pysam's bcftools consensus dispatch which translates the variants back into the samples' haplotypes. This step has given users problems in the past due to `bcftools consensus` having a problem with the VCF's format, but not being very friendly about telling us why.

Is it possible for you to share  your input.vcf.gz? I could debug it to see if there's anything that jumps out. If you cannot share it, let me know and I'll need to spend a few hours writing documentation to teach you how to debug it

Have a great day,
~/Adam

**Comment by ACEnglish** [comment]
Making notes for posterity here regarding the follow up email

1) INFO/END being ill defined breaks bcftools consensus
2) pysam 0.19 doesn't seem to hang, updated truvari's minimum requirement
3) Running bcftools norm without `--do-not-normalize` might be a gamble

**Comment by andy941** [comment]
Leaving this here for future reference.

When dealing with VCFs in CNV:TR format, this commands allow to translate the calls into something that works with bench+refine (I split it in intermediate steps for clarity).

``` bash
# split multi allelic variants
bcftools norm -m-any -N -o 1_split_variants.vcf

# populate the REF and ALT fields with putative repeats and the INFO fields with minimal information. For example, if REF has 4 copies and ALT 5 copies of the GCC pattern:
REF                 ALT                INFO
AGCCGCCGCCGCC       AGCCGCCGCCGCCGCC   SVTYPE=INS;SVLEN=3;RUS=GCC ...
# The A is the base before the variant on the reference (REF field in the CNV:TR format)

# sort 
bcftools sort $@/2_fill_ref_alt.vcf -o $@/3_sorted.vcf
bgzip -c $@/3_sorted.vcf > $@/3_sorted.vcf.gz
tabix -p vcf $@/3_sorted.vcf.gz

# correct the REF field to be the same as the reference sequence (required by bcftools consensus to work)
bcftools +fill-from-fasta 3_sorted.vcf.gz -- -c REF -f $(GENOME_FASTA) > 4_fix_ref.vcf
```

A couple of things to keep in mind:
- the reason for the hang is bcftools consensus failing to retrieve the haplotype sequence. to make troubleshooting easier, one can just run the `bcftools consensus -H1 -f $(GENOME_FASTA)` command alone to get more meaningful errors
- I still get the hang in truvari with `pysam 0.21`
- one sneaky problem is also duplicate records that cause `bcftools consensus` to fail and truvari to hang
- Be wary of running bcftools norm **without** the `-N` option, it could mess up the records in unpredictable ways

**Comment by kokyriakidis** [comment]
@ACEnglish Truvari refine hangs indefinitely even using the 4.1.1.dev version and pysam 0.22. It hangs mostly when I use the TR benchmark. When I use the CMRG SV benchmark it works ok. Any sugestions?

**Comment by ACEnglish** [comment]
I don't have enough information to provide a useful answer.

* Did you attempt his note on "the reason for the hang is bcftools consensus failing to retrieve the haplotype sequence. to make troubleshooting easier, one can just run the bcftools consensus -H1 -f $(GENOME_FASTA) command alone to get more meaningful errors"? 
* What about "one sneaky problem is also duplicate records that cause bcftools consensus to fail and truvari to hang"?
* Are you using the same input VCF for your runs against CMRG and the TR benchmark? If not, what is different about them?
