### ISSUE TITLE
Clarification on how variant grouping and phasing are handled during Truvari analysis

### ISSUE THREAD

**Issue by TimD1** [ACEnglish/truvari#171]
Hi Adam,

**Variant Grouping**
I skimmed the `phab` module a while ago, and it seemed that variants were grouped by BED region. Is that correct? Do MAFFT and WFA perform refinement for all variants at once within a single BED region? And is this grouping handled the same way for both `phab` and `refine`?

**Variant Phasing**
My current understanding is that Truvari assumes both input VCFs are completely phased, and enforces local phasing between adjacent variants within the same group. Is this correct (or is global phasing enforced)? My current interpretation is that Truvari will enforce correct local phasing of all variants within a BED region (not allowing switch or flip errors). Is that right? If so, are switch errors allowed between BED regions?

Thanks,
Tim

**Comment by ACEnglish** [comment]
Yes, phab works on regions and all variants are assumed to be phased over the region.
