### ISSUE TITLE
Can Truvari read out query coordinates of duplications from .vcf file?

### ISSUE THREAD

**Issue by 1123231323232** [ACEnglish/truvari#172]
Hello,

I am a master student in the area of genomics and I am using Truvari in my automated SV calling pipeline. I think it is a great tool, however, I was wondering how Truvari handles the coordinates of the query genome for duplications, since for example the duplicated sequence can be on some distant location, and only on the query. Is there some tag in the INFO field of the .vcf file, which can contain this info for Truvari?

And as a secondary question, if it is not the case that Truvari considers that: What is your estimate how difficult it is to change the source code myself and introduce such a functionality? Additionally, I would also like that Truvari benchmarks translocations, and for them the same problem exists, that the coordinates of the query genome are essential to benchmark this SV correctly.

Thank you very much for your time and effort!

Best,

Thomas

**Comment by ACEnglish** [comment]
Hello,

If your DUP has start/end information in its VCF entry, Truvari will compare that information to events at that same location. Generally, DUPs aren't a sequence-resolved variant and should therefore be compared without sequence similarity (e.g. `--pctseq 0` [docs](https://github.com/ACEnglish/truvari/wiki/bench#svs-without-sequences)). Translocations (BNDs) are not recommended for comparison by Truvari.

Have a great day,
~/Adam English
