### ISSUE TITLE
Collapsing results of one sample from multiple SV callers

### ISSUE THREAD

**Issue by jyw-atgithub** [ACEnglish/truvari#174]
Dear @ACEnglish ,
I am trying to coppalse results of one sample from multiple SV callers. According to current manual, the `--intra` option does this job. However, when I am using it , the program showed:

```
collapse: error: unrecognized arguments: --intra
```

I am using the latest version of Truvari from pip. My script was :

```bash
truvari collapse --intra  -k maxqual --sizemax 50000000 \
-i {con_SVs}/${name}.3.vcf.gz -o ${con_SVs}/${name}.con.vcf \
-c ${con_SVs}/${name}.collapsed.vcf -f ${ref_genome}
```

May I know the current way to do it? Thank you!
Best, 

Jen-Yu

**Comment by ACEnglish** [comment]
I suspect you're using `<=4.1` while the `--intra` option was just added ([updates](https://github.com/ACEnglish/truvari/wiki/Updates#truvari-42)) and is only available as a [release candidate](https://github.com/ACEnglish/truvari/releases/tag/v4.2.0-rc) right now or can be installed directly from develop ([details](https://github.com/ACEnglish/truvari/wiki/Installation#manual-installation)).

**Comment by jyw-atgithub** [comment]
Hi! 
Thank you for your quick response! I was using v4.1.0 and I am switching to v4.2.0-rc. Have a good day!
