### ISSUE TITLE
`truvari collapse`  with `--intra` option results in pysam throwing `TypeError: value expected to be scalar, given len=2`

### ISSUE THREAD

**Issue by jsquaredosquared** [ACEnglish/truvari#178]
**Version** : 
Truvari v4.2.0-rc

**Describe the bug** : 
I am unable to run `truvari collapse` to successfully combine the outputs of multiple SV callers. The command runs for a bit before pysam throws a `TypeError: value expected to be scalar, given len=2`, causing it to crash. I realize that I am using a release candidate that is still in development, but I was wondering if you wouldn't mind taking a look at the problem.

**To Reproduce** : 
```
truvari collapse \
-i <merged_vcf> \
-o <output_vcf> \
-c <collapsed_vcf> \
-f <path_to_ref> \
--intra \
-p 0 \
-S 999999999 \
--passonly
```

ERROR:
```
Traceback (most recent call last):
  File "/[...]/.venv/bin/truvari", line 8, in <module>
    sys.exit(main())
  File "/[...]/.venv/lib/python3.10/site-packages/truvari/__main__.py", line 102, in main
    TOOLS[args.cmd](args.options)
  File "/[...]/.venv/lib/python3.10/site-packages/truvari/collapse.py", line 654, in collapse_main
    outputs.write(call, args.median_info)
  File "/[...]/.venv/lib/python3.10/site-packages/truvari/collapse.py", line 596, in write
    self["output_vcf"].write(collap.entry)
  File "/[...]/.venv/lib/python3.10/site-packages/truvari/collapse.py", line 541, in write
    entry = self.consolidate(entry)
  File "/[...]/.venv/lib/python3.10/site-packages/truvari/collapse.py", line 529, in consolidate
    entry.samples[0][k] = fmt[k]
  File "pysam/libcbcf.pyx", line 3544, in pysam.libcbcf.VariantRecordSample.__setitem__
  File "pysam/libcbcf.pyx", line 876, in pysam.libcbcf.bcf_format_set_value
  File "pysam/libcbcf.pyx", line 598, in pysam.libcbcf.bcf_check_values
TypeError: value expected to be scalar, given len=2
```

**Expected behavior** : 
Successful merging of results from multiple SV callers from a single sample.

**Example Data** : 
N/A

**Additional context** :
The callers to be merged are Manta, TARDIS, and CNVpytor.

**Comment by ACEnglish** [comment]
Hello,

I can't tell from the error exactly what's happening. The line throwing the error is trying to consolidate a FORMAT field, but one sample has a format that's a tuple (e.g. `##FORMAT,Number=A`) but the other has scalar (e.g. `##FORMAT,Number=1`). Is there any chance that the callers have conflicting FORMAT field definitions in their headers? If its possible to share the data, I could probably hunt down the problem.

Have a great day,
~/Adam English

**Comment by jsquaredosquared** [comment]
Hi Adam,

I have just checked, Manta and TARDIS have conflicting FORMAT field definitions:

- Manta:

```
##FORMAT=<ID=SR,Number=.,Type=Integer,Description="Split reads for the ref and alt alleles in the order listed, for reads where P(allele|read)>0.999">
```

- TARDIS:

```
##FORMAT=<ID=SR,Number=1,Type=Integer,Description="Split Read Support">
```

**Comment by jsquaredosquared** [comment]
Here are the VCF files I am trying to merge:
https://drive.google.com/drive/folders/1DYe5v8dvA53tOUQgFJW5WN6oAVq3YO91?usp=sharing

**Comment by ACEnglish** [comment]
I think the easiest fix would be to redefine the TARDIS FORMAT with 
```
##FORMAT=<ID=SR,Number=.,Type=Integer,Description="Split Read Support">
```

Out of curiosity, did the `bcftools merge` step throw any warnings about that conflicting field? I would have expected it to catch that. I'll have to think about putting a header-checker step in Truvari. Generally I've tried to keep the assumption that VCF files are valid. But I don't know if redundant/conflicting headers are prevented by VCF format specs.

**Comment by jsquaredosquared** [comment]
Thanks, `bcftools merge` did indeed catch it:

```
[W::bcf_hdr_merge] Trying to combine "SR" tag definitions of different lengths
[W::bcf_hdr_merge] Trying to combine "SVLEN" tag definitions of different lengths
[W::tbx_parse1] VCF INFO/END=31061143 is smaller than POS at chr20:31061143
This tag will be ignored. Note: only one invalid END tag will be reported.
[W::vcf_parse_info] INFO/END=31061143 is smaller than POS at chr20:31061144
```

**Comment by ACEnglish** [comment]
Cool, thanks for letting me know. 

BTW, if you're not performing sequence similarity (`-p 0`) you don't have to provide the reference `-f`. Also, if you are checking sequence similarity, you don't have to provide the reference ([detail](https://github.com/ACEnglish/truvari/wiki/bench#comparing-sequences-of-variants)).
