### ISSUE TITLE
One  new annotation added by `truvari collapse` ?

### ISSUE THREAD

**Issue by jyw-atgithub** [ACEnglish/truvari#179]
Hi @ACEnglish , 
I am using the version "4.2.0-rc". When I am inspecting the out put vcf file (from `-o` ) There are three tags added. For example, 

```
NumCollapsed=1;NumConsolidated=1;CollapseId=1.1
NumCollapsed=1;NumConsolidated=1;CollapseId=3.1
NumCollapsed=3;NumConsolidated=4;CollapseId=54.3
```

While `CollapseId`  and `NumCollapsed` are mentioned in wiki page, `NumConsolidated` seems to be new.  I don't get it by reading this segement, `self.entry.info["NumConsolidated"] = self.gt_consolidate_count` May I know the meaning for this? Thank you!
Best, 

Jen-Yu

**Comment by ACEnglish** [comment]
NumCollapsed is defined in the header as "Number of samples consolidated into this call by truvari". I've added this to the wiki. This number is how many genotypes are consolidated into the kept variant. For example,  if there are two variants which collapse would identify as redundant:

```
#CHROM POS ...  SAMP1  SAMP2  SAMP3
chr1  1234 ...   1/1   ./.    ./.
chr1  1235 ...   ./.   1/1    1/1
```
Would output:
```
#CHROM POS ...  SAMP1  SAMP2  SAMP3
chr1  1234 ...  1/1    1/1    1/1
```
Which is two consolidated genotypes.
