### ISSUE TITLE
Pysam bug results in missing info field in output VCF file.

### ISSUE THREAD

**Issue by zhengxinchang** [ACEnglish/truvari#183]
**Version** : 

Use `truvari version` to get the version you're using. If the version ends in `*-dev`, report the `git show-ref --hash HEAD` of the repository you're working on.

Truvari v4.1.0 

**Describe the bug** : 

Dear Adam,

I recently utilized the latest version of Truvari for processing a VCF file. The tool functioned effectively, but I encountered an issue that I believe warrants attention. Specifically, while using the bench command to identify intersections between two VCF files, I observed a bug related to the reporting of the original info field in the output VCF.

For reference, one of the VCF files I employed was sourced from the NCBI database: [HG002_SVs_Tier1_v0.6.vcf.gz](https://ftp.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/NIST_SV_v0.6/HG002_SVs_Tier1_v0.6.vcf.gz). I noticed that the "END" field in the info section, which is present in the HG002_SVs_Tier1_v0.6.vcf.gz file, was missing in the output VCF generated by Truvari.

To further investigate, I conducted an independent test using the latest version of pysam and confirmed that this issue stems from the entry.translate() function. Although this might not be a direct bug within Truvari itself, I thought it important to bring to your attention for potential rectification in future updates.

Thank you for your attention to this matter.

Best regards,
Xinchang

**To Reproduce** : 
Steps/Commands to reproduce the behavior with stdout/stderr log lines when reasonable/necessary.

1. download [HG002_SVs_Tier1_v0.6.vcf.gz](https://ftp.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/NIST_SV_v0.6/HG002_SVs_Tier1_v0.6.vcf.gz).

2. install latest Pysam with v0.22.0

3.  execute:
```
a = pysam.VariantFile("./HG002_SVs_Tier1_v0.6.vcf")
list(a.header.info.items())
x = next(a)
x.translate(a.header)
list(x.info.iterkeys())
```

line 2 will return: 
![image](https://github.com/ACEnglish/truvari/assets/16239108/0d194148-11a3-4c9f-b57a-335bbd837de8)

line 5 will return:
![image](https://github.com/ACEnglish/truvari/assets/16239108/b95a8e32-7045-4caf-9c6c-86fd40b60542)

`END` is missed in line 5 output.

**Expected behavior** : 

All items in INFO field should exist in output vcf file.

**Example Data** : 
If applicable/possible, add example data to help recreate your problem.

 [HG002_SVs_Tier1_v0.6.vcf.gz](https://ftp.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/NIST_SV_v0.6/HG002_SVs_Tier1_v0.6.vcf.gz).

**Additional context** :

**Comment by ACEnglish** [comment]
See https://github.com/pysam-developers/pysam/issues/659#issuecomment-468673867

This is known pysam behavior. The END tag is redundant with sequence resolved SVs and pysam removes it. If you attempt to do something like `bcftools query -f "%CHROM\t%POS\t%END\n" no_end.vcf.gz` you'll notice it works.

**Comment by thedam** [comment]
Ok, so are there plans to fix this known pysam behavior?
I'd like to create a new vcf file, based on the filtered old one, and I'd like to have the "END" tag in the output vcf file...

**Comment by ACEnglish** [comment]
I do not maintain pysam. Also, if you read the answer #222 you'll understand that END being 'dropped' is part of the vcf format specification, which I also do not maintain.
