### ISSUE TITLE
Calculate SNV

### ISSUE THREAD

**Issue by xiaomiyongyuan** [ACEnglish/truvari#197]
Hello, I want to know if this tool can be used for SNV result detection on the hg002 dataset, and why am I getting mostly erroneous SNV results when using the following parameters?(The length of variants in my input dataset are all less than 50bp, with 99% being SNVs.)
"--pctsim 0 -o out --sizemin 0 --sizefilt 1 --pctsize 0.1 --refdist 1 --sizemax 1"
2024-02-19 22:14:18,357 [INFO] Stats: {
    "TP-base": 1,
    "TP-call": 1,
    "FP": 46,
    "FN": 47,
    "precision": 0.02127659574468085,
    "recall": 0.020833333333333332,
    "f1": 0.021052631578947368,
    "base cnt": 48,
    "call cnt": 47,
    "TP-call_TP-gt": 1,
    "TP-call_FP-gt": 0,
    "TP-base_TP-gt": 1,
    "TP-base_FP-gt": 0,
    "gt_concordance": 1.0
}

**Comment by ACEnglish** [comment]
We currently only recommend using Truvari to compare variants ≥ ~20bp or variants ≥5bp in narrowly defined regions such as [TRs](https://www.biorxiv.org/content/10.1101/2023.10.29.564632v1). We have in our development roadmap implementing and fully validating <5bp variants. 

However, it is possible to compare smaller variants, it just may create inaccurate results. Your parameters are close to what would be needed to test out tiny variant comparison. 

1) `--sizemin` shouldn't be less than `--sizefilt`. Either set both to `0` or just provide `--sizemin 0` and `--sizefilt` is automatically set to `0`.
2) I would recommend keeping sequence similarity on by not providing `--pctsim 0`. Otherwise an e.g. T may  match to an A. But if allowing these types of matches is part of your experiment. you can keep `--pctsim 0`
3) The same thing goes for `--pctsize`. I would just leave the defaults. 
4) `--sizemax` is a ≤ limit, so 1bp INDELs are being analyzed by when given these parameters. That would also need to be set to `0` if you wanted to only look at SNVs.

That should get you a different answer. But again, we cannot vouch for its validity. The ability of Truvari to compare tiny variants should not be confused with any kind of proficiency. 

Tools that are built for small variants include [rtg vcfeval](https://github.com/RealTimeGenomics/rtg-tools) for all VCFs and [vcfdist](https://github.com/TimD1/vcfdist) for phased VCFs.

**Comment by xiaomiyongyuan** [comment]
2024-02-19 23:16:22,189 [INFO] Params:
{
    "base": "sorthg002benend.vcf.gz",
    "comp": "sorthg002benend.vcf.gz",
    "output": "out",
    "reference": null,
    "giabreport": false,
    "debug": false,
    "prog": false,
    "refdist": 500,
    "pctsim": 0.0,
    "buffer": 0.1,
    "pctsize": 0.7,
    "pctovl": 0.0,
    "typeignore": false,
    "use_lev": false,
    "gtcomp": false,
    "bSample": null,
    "cSample": null,
    "sizemin": 0,
    "sizefilt": 0,
    "sizemax": 0,
    "passonly": false,
    "no_ref": false,
    "includebed": null,
    "multimatch": false
}
2024-02-19 23:16:22,191 [INFO] Creating call interval tree for overlap search
2024-02-19 23:16:22,193 [INFO] 50 call variants in total
2024-02-19 23:16:22,193 [INFO] 46 call variants within size range (0, 0)
2024-02-19 23:16:22,194 [INFO] Matching base to calls
2024-02-19 23:16:22,211 [WARNING] No TP or FP calls in comp!
2024-02-19 23:16:22,211 [INFO] Parsing FPs from calls
2024-02-19 23:16:22,212 [WARNING] No TP or FP calls in comp!
2024-02-19 23:16:22,212 [INFO] Stats: {
    "TP-base": 0,
    "TP-call": 0,
    "FP": 0,
    "FN": 46,
    "precision": 0,
    "recall": 0,
    "f1": "NaN",
    "base cnt": 46,
    "call cnt": 0,
    "TP-call_TP-gt": 0,
    "TP-call_FP-gt": 0,
    "TP-base_TP-gt": 0,
    "TP-base_FP-gt": 0,
    "gt_concordance": 0
}
2024-02-19 23:16:22,212 [INFO] Finished bench

**Comment by ACEnglish** [comment]
Oh, it looks like you're using an older version of Truvari. Using v4.2.1 I ran `truvari bench -s 0 -b tiny.vcf.gz -c tiny.vcf.gz -o delme` on the below 157 variants and they all matched
```
    TP-base: 157,
    TP-comp: 157,
    FP: 0,
    FN: 0,
    precision: 1.0,
    recall: 1.0,
    f1: 1.0,
    base cnt: 157,
    comp cnt: 157,
```

VCF:
<details><summary>Details</summary>
<p>

##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=chr1,length=248956422>
##contig=<ID=chr2,length=242193529>
##contig=<ID=chr3,length=198295559>
##contig=<ID=chr4,length=190214555>
##contig=<ID=chr5,length=181538259>
##contig=<ID=chr6,length=170805979>
##contig=<ID=chr7,length=159345973>
##contig=<ID=chr8,length=145138636>
##contig=<ID=chr9,length=138394717>
##contig=<ID=chr10,length=133797422>
##contig=<ID=chr11,length=135086622>
##contig=<ID=chr12,length=133275309>
##contig=<ID=chr13,length=114364328>
##contig=<ID=chr14,length=107043718>
##contig=<ID=chr15,length=101991189>
##contig=<ID=chr16,length=90338345>
##contig=<ID=chr17,length=83257441>
##contig=<ID=chr18,length=80373285>
##contig=<ID=chr19,length=58617616>
##contig=<ID=chr20,length=64444167>
##contig=<ID=chr21,length=46709983>
##contig=<ID=chr22,length=50818468>
##contig=<ID=chrX,length=156040895>
##contig=<ID=chrY,length=57227415>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="SVTYPE">
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="SVLEN">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HG002.H1
chr1	688908	.	G	C	60	PASS	.	GT	0/0
chr1	688948	.	G	T	60	PASS	.	GT	0/0
chr1	689063	.	T	A	60	PASS	.	GT	0/0
chr1	689088	.	A	G	60	PASS	.	GT	0/0
chr1	689236	.	G	T	60	PASS	.	GT	0/0
chr1	689239	.	G	A	60	PASS	.	GT	0/0
chr1	689334	.	T	C	60	PASS	.	GT	0/0
chr1	689344	.	G	GA	60	PASS	.	GT	0/0
chr1	689436	.	G	A	60	PASS	.	GT	0/0
chr1	689520	.	T	C	60	PASS	.	GT	0/0
chr1	689541	.	C	A	60	PASS	.	GT	0/0
chr1	689749	.	C	G	60	PASS	.	GT	0/0
chr1	689761	.	T	TA	60	PASS	.	GT	0/0
chr1	689803	.	G	A	60	PASS	.	GT	0/0
chr1	689819	.	C	T	60	PASS	.	GT	0/0
chr1	689933	.	A	C	60	PASS	.	GT	0/0
chr1	689962	.	C	T	60	PASS	.	GT	0/0
chr1	689991	.	T	C	60	PASS	.	GT	0/0
chr1	690012	.	T	C	60	PASS	.	GT	0/0
chr1	690021	.	C	T	60	PASS	.	GT	0/0
chr1	690039	.	G	T	60	PASS	.	GT	0/0
chr1	690060	.	A	C	60	PASS	.	GT	0/0
chr1	690092	.	C	CT	60	PASS	.	GT	0/0
chr1	690098	.	G	T	60	PASS	.	GT	0/0
chr1	690136	.	A	G	60	PASS	.	GT	0/0
chr1	690169	.	A	G	60	PASS	.	GT	0/0
chr1	690272	.	G	C	60	PASS	.	GT	0/0
chr1	690344	.	A	G	60	PASS	.	GT	0/0
chr1	690432	.	A	G	60	PASS	.	GT	0/0
chr1	690714	.	T	A	60	PASS	.	GT	0/0
chr1	690854	.	G	A	60	PASS	.	GT	0/0
chr1	690941	.	A	G	60	PASS	.	GT	0/0
chr1	691056	.	C	CA	60	PASS	.	GT	0/0
chr1	691199	.	G	A	60	PASS	.	GT	0/0
chr1	691306	.	CCT	C	60	PASS	.	GT	0/0
chr1	691319	.	T	C	60	PASS	.	GT	0/0
chr1	691405	.	A	C	60	PASS	.	GT	0/0
chr1	692064	.	C	T	60	PASS	.	GT	0/0
chr1	692574	.	T	C	60	PASS	.	GT	0/0
chr1	692760	.	T	C	60	PASS	.	GT	0/0
chr1	693086	.	A	C	60	PASS	.	GT	0/0
chr1	693190	.	C	A	60	PASS	.	GT	0/0
chr1	693461	.	G	C	60	PASS	.	GT	0/1
chr1	693681	.	C	A	60	PASS	.	GT	0/0
chr1	694044	.	T	C	60	PASS	.	GT	0/0
chr1	694627	.	T	C	60	PASS	.	GT	0/0
chr1	695296	.	G	A	60	PASS	.	GT	0/0
chr1	695396	.	A	G	60	PASS	.	GT	0/0
chr1	695433	.	T	C	60	PASS	.	GT	0/0
chr1	696021	.	C	T	60	PASS	.	GT	0/0
chr1	696276	.	C	CA	60	PASS	.	GT	0/0
chr1	696741	.	A	C	60	PASS	.	GT	0/0
chr1	696779	.	G	A	60	PASS	.	GT	0/0
chr1	696851	.	C	G	60	PASS	.	GT	0/0
chr1	696869	.	A	G	60	PASS	.	GT	0/0
chr1	696963	.	C	G	60	PASS	.	GT	0/0
chr1	697028	.	T	C	60	PASS	.	GT	0/0
chr1	697051	.	T	C	60	PASS	.	GT	0/0
chr1	697250	.	A	G	60	PASS	.	GT	0/0
chr1	697586	.	T	C	60	PASS	.	GT	1/1
chr1	698202	.	C	T	60	PASS	.	GT	1/1
chr1	698667	.	G	A	60	PASS	.	GT	0/0
chr1	699030	.	G	A	60	PASS	.	GT	1/1
chr1	699033	.	C	T	60	PASS	.	GT	1/1
chr1	699078	.	A	G	60	PASS	.	GT	1/1
chr1	699236	.	C	T	60	PASS	.	GT	1/1
chr1	699298	.	TG	T	60	PASS	.	GT	1/1
chr1	699538	.	C	T	60	PASS	.	GT	1/1
chr1	700073	.	C	T	60	PASS	.	GT	0/0
chr1	700155	.	C	T	60	PASS	.	GT	1/1
chr1	700421	.	G	A	60	PASS	.	GT	0/0
chr1	700500	.	A	G	60	PASS	.	GT	0/0
chr1	700537	.	A	G	60	PASS	.	GT	1/1
chr1	700606	.	A	G	60	PASS	.	GT	0/0
chr1	700712	.	T	G	60	PASS	.	GT	1/1
chr1	700905	.	T	C	60	PASS	.	GT	0/0
chr1	700918	.	T	C	60	PASS	.	GT	0/0
chr1	700938	.	G	A	60	PASS	.	GT	1/1
chr1	701595	.	G	A	60	PASS	.	GT	0/0
chr1	702960	.	G	A	60	PASS	.	GT	0/0
chr1	702977	.	C	A	60	PASS	.	GT	0/0
chr1	703393	.	C	T	60	PASS	.	GT	1/1
chr1	703919	.	T	C	60	PASS	.	GT	0/0
chr1	704094	.	A	G	60	PASS	.	GT	0/0
chr1	704240	.	C	T	60	PASS	.	GT	1/1
chr1	704306	.	A	C	60	PASS	.	GT	1/1
chr1	704543	.	A	G	60	PASS	.	GT	1/1
chr1	704780	.	T	C	60	PASS	.	GT	0/0
chr1	705172	.	T	C	60	PASS	.	GT	0/0
chr1	705491	.	A	C	60	PASS	.	GT	1/1
chr1	705793	.	C	T	60	PASS	.	GT	0/0
chr1	705856	.	A	C	60	PASS	.	GT	0/0
chr1	706138	.	T	G	60	PASS	.	GT	0/0
chr1	707008	.	T	C	60	PASS	.	GT	0/0
chr1	707496	.	C	T	60	PASS	.	GT	0/0
chr1	707497	.	G	A	60	PASS	.	GT	0/0
chr1	707895	.	G	A	60	PASS	.	GT	1/1
chr1	708085	.	C	A	60	PASS	.	GT	1/1
chr1	708143	.	C	CA	60	PASS	.	GT	0/0
chr1	708448	.	G	A	60	PASS	.	GT	0/0
chr1	709509	.	T	C	60	PASS	.	GT	0/0
chr1	710579	.	T	TAAAGAACTGCCCGGCCGGGCGCGGTGGCTCACGCCTGTAATCCCAGCACTTTGGGAGGCCGAGGCGGGCGGATCACGAGGTCAGGAGATCGAGACCATCCCGGCTAAAACGGTGAAACCCCGTCTCTACTAAAAATACAAAAAATTAGCCGGGCGTAGTGGCGGGCGCCTGTAGTCCCAGCTACTTGGGAGGCTGAGGCAGGAGAATGGCGTGAACCCGGGAGGTGGAGCTTGCAGTGAGCCGAGATCCCGCCACTGCACTCCAGCCTGGGCGACAGAGCGAGACTCCGTCTCAAAAAAAAAAAAAAAAAAAAAAAAAAA	60	PASS	SVTYPE=INS;SVLEN=320	GT	1/1
chr1	710579	.	T	TAAAGAACTGCCCGGCCGGGCGCGGTGGCTCACGCCTGTAATCCCAGCACTTTGGGAGGCCGAGGCGGGCGGATCACGAGGTCAGGAGATCGAGACCATCCCGGCTAACACGGTGAAACCCCGTCTCTACTAAAAATACAAAAAATTAGCCGGGCGTAGTGGCGGGCGCCTGTAGTCCCAGCTACTTGGGAGGCTGAGGCAGGAGAATGGCGTGAACCCGGGAGGTGGAGCTTGCAGTGAGCCGAGATCCCGCCACTGCACTCCAGCCTGGGCGACAGAGCGAGACTCCGTCTCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA	60	PASS	SVTYPE=INS;SVLEN=344	GT	0/0
chr1	710579	.	T	TAAAGAACTGCCCGGCCGGGCGCGGTGGCTCACGCCTGTAATCCCAGCACTTTGGGAGGCCGAGGCGGGCGGATCACGAGGTCAGGAGATCGAGACCATCCCGGCTAAAACGGTGAAACCCCGTCTCTACTAAAAATACAAAAAATTAGCCGGGCGTAGTGGCGGGCGCCTGTAGTCCCAGCTACTTGGGAGGCTGAGGCAGGAGAATGGCGTGAACCCGGGAGGTGGAGCTTGCAGTGAGCCGAGATCCCGCCACTGCACTCCAGCCTGGGCGACAGAGCGAGACTCCGTCTCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA	60	PASS	SVTYPE=INS;SVLEN=336	GT	0/0
chr1	710579	.	T	TAAAGAACTGCCCGGCCGGGCGCGGTGGCTCACGCCTGTAATCCCAGCACTTTGGGAGGCCGAGGCGGGCGGATCACAAGGTCAGGAGATCGAGACCATCCCGGCTAAAACGGTGAAACCCCGTCTCTACTAAAAATACAAAAAATTAGCCGGGCGTAGTGGCGGGCGCCTGTAGTCCCAGCTACTTGGGAGGCTGAGGCAGGAGAATGGCGTGAACCCGGGAGGTGGAGCTTGCAGTGAGCCGAGATCCCGCCACTGCACTCCAGCCTGGGCGACAGAGCGAGACTCCGTCTCAAAAAAAAAAAAAAAAAAAAAAAAAAA	60	PASS	SVTYPE=INS;SVLEN=320	GT	0/0
chr1	710579	.	T	TAAAGAACTGCCCGGCCGGGCGCGGTGGCTCACGCCTGTAATCCCAGCACTTTGGGAGGCCGAGGCGGGCGGATCACGAGGTCAGGAGATCGAGACCATCCCGGCTAAAACGGTGAAACCCCGTCTCTACTAAAAATACAAAAAATTAGCCGGGCGTAGTGGCGGGCGCCTGTAGTCCCAGCTACTTGGGAGGCTGAGGCAGGAGAATGGCGTGAACCCGGGAGGTGGAGCTTGCAGTGAGCCGAGATCCCGCCACTGCACTCCAGCCTGGGCGACAGAGCGAGACTCCGTCTCAAAAAAAAAAAAAAAAAAAAAAAAAA	60	PASS	SVTYPE=INS;SVLEN=319	GT	0/0
chr1	710856	.	C	G	60	PASS	.	GT	0/0
chr1	711235	.	C	T	60	PASS	.	GT	0/0
chr1	711761	.	A	G	60	PASS	.	GT	0/0
chr1	711958	.	TTATATATTATATATCTATTATATATAATATTATATATCTATTATATATTATATATTGTATATCTATTACATATATATTATATATGTATTA	T	60	PASS	SVTYPE=DEL;SVLEN=90	GT	0/0
chr1	712048	.	A	ATATATAT	60	PASS	.	GT	1/1
chr1	712228	.	C	CT	60	PASS	.	GT	1/1
chr1	712344	.	G	A	60	PASS	.	GT	0/0
chr1	712480	.	C	T	60	PASS	.	GT	0/0
chr1	713463	.	TATTA	T	60	PASS	.	GT	0/0
chr1	713495	.	A	AAT	60	PASS	.	GT	0/0
chr1	713733	.	C	T	60	PASS	.	GT	1/1
chr1	713773	.	TAA	T	60	PASS	.	GT	0/0
chr1	713812	.	A	T	60	PASS	.	GT	0/0
chr1	714324	.	GTAGAAGAATATGAGACATTTCCCTAATCATTATGTGTAATTACAATTACA	G	60	PASS	SVTYPE=DEL;SVLEN=50	GT	1/1
chr1	714355	.	TATGTGTAATTACAATTACATAGAAGAATATGAGACATTTCCCTAATCATTATGTGTAATTACAATTACATATATATATGTAATTGTAATTACACATA	T	60	PASS	SVTYPE=DEL;SVLEN=97	GT	0/0
chr1	714679	.	G	A	60	PASS	.	GT	0/0
chr1	714717	.	A	G	60	PASS	.	GT	1/1
chr1	714817	.	A	T	60	PASS	.	GT	0/0
chr1	715674	.	A	G	60	PASS	.	GT	1/1
chr1	715769	.	C	T	60	PASS	.	GT	1/1
chr1	715831	.	C	CAAAAAAAA	60	PASS	.	GT	0/0
chr1	716477	.	T	C	60	PASS	.	GT	0/0
chr1	717447	.	G	GA	60	PASS	.	GT	0/0
chr1	717682	.	TA	T	60	PASS	.	GT	1/1
chr1	718138	.	A	AAG	60	PASS	.	GT	1/1
chr1	718346	.	A	G	60	PASS	.	GT	0/0
chr1	718642	.	A	C	60	PASS	.	GT	0/0
chr1	718949	.	A	G	60	PASS	.	GT	0/0
chr1	720012	.	G	A	60	PASS	.	GT	0/0
chr1	720654	.	CT	C	60	PASS	.	GT	1/1
chr1	720963	.	A	G	60	PASS	.	GT	0/0
chr1	721646	.	G	A	60	PASS	.	GT	0/0
chr1	721662	.	G	A	60	PASS	.	GT	0/0
chr1	721920	.	G	C	60	PASS	.	GT	0/0
chr1	722169	.	T	G	60	PASS	.	GT	0/0
chr1	722252	.	GAGTCTC	G	60	PASS	.	GT	1/1
chr1	722408	.	G	C	60	PASS	.	GT	1/1
chr1	722803	.	A	G	60	PASS	.	GT	0/0
chr1	723038	.	A	G	60	PASS	.	GT	0/0
chr1	724417	.	C	T	60	PASS	.	GT	0/0
chr1	724698	.	G	A	60	PASS	.	GT	1/0
chr1	724712	.	A	G	60	PASS	.	GT	0/1
chr1	724785	.	A	G	60	PASS	.	GT	0/0
chr1	724994	.	CTTCTCCCAGGTGAAGCCATTTAATCCTTTCAGTTTGGGACGGAGTAAGGCCTTCCTCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTGAGACCGAGTCTTGCTCTGTCGCCCAGGCTGGAGTGCAGTGGTGCGATCTTGGCTCACTGCAACCTCTTCCCGCCGGGTTCACGCCATTCTCCTGCCTCAGCCTTCCGGGTAGCTAGGATTACAGGTGGACGCTACCACGTCCGGCTAATTTTTGTATTTTTAGTACAGACGGGGCTTCATCATCTTGGCCAGGCTGATTTCGATCTCCTGACATCGTGATCTGCCTGCCTCCCCCTCCCAAAGTGCTGGGATTACAGGCGTGAGCCACCACGCCTGGCCAAGGCCTGCTCCTCTTATCTATACCCCCTACCCCTGCAGCTGTGCCGGGGGAAAGCTGGGCAGTTTCCCTCCTCCGAGCCCCTGTACATACCATGAATTGTGGGACCTTCAGAGCTTTTCACTTTTCGGAAAATAGCTCCTGCTGGGGCTACAAGATGGAGTGTGAAGAGGGCCTTGGGCCACAGGGAGGCGCCTGTGGACTAGGGGGAGTTCATGCACCCCTTCTTTCCCCAGAGGGGCTGGACTCAGGTGAGTATGGGGGTGGGGGCTCCTGCACTTCGACACAGGCAGCGGGAGGGTTTTCTCCCCATTCCCTCTGCACTCCCAACTTGAGCTATACTTTTTAAGAAAGTGATTCACCCTGCCTTTGCCCCCTTCCCCAGAACAGAACACGTTGATCGTGGGCGATATTTTTCATTGTGCCAAAAAGTTGCCATGACCGTCATTAAACCTGTTTAACACCAAATAATAAGGAAAATAAAATAAAAAATTCGGGCTTGGCGCAGAAACTCACTCCAAATAAATTACCTATCAAAATATTTACATAATGGTGGAAATATTCCAAAATTCAATATTTTGGGATTTATACACAAAAGATAAACAAATTAGAGGCCAAGAGGCTGCCGGAAGGGAAAAACGGGGCCTGGAATGGCCGACGTGAGGAATGAGCTGGGCCTAAAGAGGCCACTGGCAGGCAGGAGCTGGACCTGCCGAAGTGGCCGAAAGGCAGGAGCTTTGGACTGGGGAGGCCGCAGTGAGGCGAGAGCTAGCTGGGCGTGGAGAGTCTGCTGTGAGGCCGAGGCCGAGGCCGGGCCCGTGCAGGCCTTCGAGAGGCAGGAGGCCGGGCCTGCAAAGGCCGACTGGAGATCAAGTTCTGCGCCTGAAGAGGCTGCCAAAAGTCAAAAGCGGGGCCTGGGAAGGCCGCCGAGAGCCATGAGCTGGGCTGGGCCGAAAGAGGCCACTGGGAGGCAGGAGGAGCTGGGCCTGGAGAGGCTGACTCGAGGAAGTTTTGCACCTGGAGAGGCCGTCGAGAGGACGGAGCTGGGCCCAGGGAGGCCGACTTGCTGCTCTTCCAGGCCCACTTCCAGGCCGACTTGAGGACGACTTGGGCCTGCAGAGGCCGCCGGGAGGCTGGAGCTAAGCCTGGAGAGACTGACTTCGGGACGATTTGGGCCTGCAGAGGCCGCCGGGAGGCCCAAGCTGGGCCTAGAGGAGCCCACCGACCGGAGGCCATTTGGGGCCTGCAGATGTCATCGGAGGGCCAGGAGCTGAGCCTGGAGAGGCCACCGCGAGGCCTGAGCTGGGCCTGGGGAGCTTGGCTTAGGGAAGTTGTGGGCCTACCAGGGCCGCTGGGAGCTGGGCAGGAGCTGAGTCCAAAGACGTTGTTGGGACCTGGAGTCGGGCCAGAGTCCGGCCTGGAGATGCAGCCGGGAGGAAGAGCTGGGCCCGGAGGGGGCGCCGGGAGGCTGCAAGTGGGTCTGAGAGGCCAACTTGAGGAGGCCTGGCCTCTGCCTCCCGCATTGCCCAGCTGTTCCTCCTGGCTGCATCTCCCACCTCCCAGCAAACAAGCTCTTTTGGCTCAGCTCCCGCCTGCGTTTGTAGACCCCGAAGTTTCTGCAACCAAGCTCTTCAGACCCACATCCCTTCTCCCAGTGACTGAACAGTCCCAGCTCCGGCTGGAGAAGGGCGTCTGCAGACCCCGCTGTTGCCTCCCAGGGGAGTCTCCAGGCCCAGCTCTCGCCCCACCGCGACCTCCCAGGCCCAAGTCCCTGCCTACCTCCCAGCAGCCCGAGTGCGATCCTGTTCCTCCCTCACGGT	C	60	PASS	SVTYPE=DEL;SVLEN=2184	GT	0/0
chr1	725051	.	C	CT	60	PASS	.	GT	1/0
chr1	725051	.	CT	C	60	PASS	.	GT	0/0
chr1	725086	.	C	G	60	PASS	.	GT	1/1
chr1	725985	.	C	T	60	PASS	.	GT	0/0
chr1	726152	.	TGAGGCC	T	60	PASS	.	GT	0/0
chr1	726649	.	G	A	60	PASS	.	GT	1/1
chr1	726821	.	G	A	60	PASS	.	GT	1/1


</p>
</details>

**Comment by xiaomiyongyuan** [comment]
Thank you for your prompt reply, it has resolved a significant issue for me. However, I still have another question. If I don't want to compare the GT column, meaning I currently don't have a phased VCF file, are there any appropriate parameters I can use to address this issue? I haven't found a suitable solution yet.

**Comment by xiaomiyongyuan** [comment]
Thank you so much for your answer !
