### ISSUE TITLE
complex genotype problem

### ISSUE THREAD

**Issue by xiaomiyongyuan** [ACEnglish/truvari#198]
Hi,
I want to know how can i process this problem:
#CHROM POS  REF ALT  QUAL FILTER INFO FORMAT 
chr1 125 T   A,G  .       .        .         .      GT     2/1

It seems that truvari cannot process it.

**Comment by ACEnglish** [comment]
See: https://github.com/ACEnglish/truvari/wiki/Multi-allelic-VCFs

Multi-allelic vcfs are on the development roadmap, but there's currently no time estimate

**Comment by xiaomiyongyuan** [comment]
Hi,

 I have a question regarding  the _HG002_GRCh38_1_22_v4.2.1_benchmark.vcf_ file(a GIAB benchmark vcf file), which contains some multi-allelic sites. For example, it includes genotypes like 1/2 or 2/1. I've been told that these can be split into two separate VCF files and then compared with us two vcf files, one representing maternal and the other paternal variants. However, in most VCF files, these genotypes are displayed as 1/2 (sorted by number size), rather than 1/2 and 2/1 (which is only seen in phased files as 1|2 and 2|1).

So, if I understand correctly, this HG002_GRCh38_1_22_v4.2.1_benchmark.vcf can be viewed as a phased file. **All variants** to the left of the "/" may be maternal or paternal, and similarly, **all variants** to the right of the "/" may be maternal or paternal. We just don't know whether the left side of "/" in **all lines** corresponds to maternal or paternal alleles.

（Because I've also seen 0/1 and 1/0 in the readme file, I wanted to inquire about them.）

Thank you for your assistance!

**Comment by ACEnglish** [comment]
I'm not familiar enough with that benchmark to give you a definitive answer. I would recommend you ask the GIAB consortium. My guess is that an order of 2/1 is equivalent to a phasing of 2|1, but that's just speculation.
