### ISSUE TITLE
Support vector for intra-sample merge

### ISSUE THREAD

**Issue by jiadong324** [ACEnglish/truvari#206]
Hi Adam,

I try to do intra-sample merge of SVs from multiple callers and want to get the support vector for each caller. I am a little bit confused about the ```collapsed.vcf``` and ```merge.vcf```. Let's say the example you gave is from two different callers.

```
>> caller-one.vcf:
chr1 1 ... GT 0/1
chr1 5 ... GT 1/1
>> caller-two.vcf:
chr1 1 ... GT 1/1
chr1 7 ... GT 0/1

>> merge.vcf:
chr1 1 ... GT 0/1 1/1
chr1 5 ... GT 1/1 ./.
chr1 7 ... GT ./. 0/1    
```

Truvari outputs:

```
>> truvari_merge.vcf
chr1 1 ... GT 0/1 1/1
chr1 5 ... GT 1/1 0/1
>> truvari_collapsed.vcf
chr1 7 ... GT ./. 0/1    
```
Here are my questions:
1. Why is ```chr1 7 ... GT ./. 0/1```  in the ```truvari_collapsed.vcf```, but ```chr1 5 ... GT 1/1 ./.``` is kept as  ```chr1 5 ... GT 1/1 0/1``` in your ```truvari_merge.vcf```?
2. Similar to ```jasmine```, I am trying to obtain the support vector for each SV from the GT columns in the output VCF. For example, I would get ```SUPP_VEC=11``` for ```chr1 5 ... GT 1/1 0/1```, since they have genotypes to their corresponding callers. Moreover, I also want to tag the caller-specific SVs (i.e., SVs only detected by one caller). Thus, what is your suggestions on this?

Looking forward to your reply! Thanks!

**Comment by ACEnglish** [comment]
The example states it is "...matching any calls within 3bp...". The variants at position 5 and and position 7 are therefore matched. The example command uses the default `--keep`, which is 'first' and therefore the position 5 variant is in the output. The second sample's genotype in the position 5 variant is altered because genotypes are consolidated during collapsing. That position 5 variant is now the kept representative of the position 7 variant and therefore inherits its genotype information. 

As for why the position 7 variant is in the truvari_collapsed.vcf, this file hold the representations which were collapsed into a kept variant representation. I may have made a mistake by naming that the `--collapsed-output` and maybe called it `--removed-output`. 

Truvari collapse populates FORMAT/SUPP flag if the `--intra` flag is set. ([details](https://github.com/ACEnglish/truvari/wiki/collapse#--intra)).  This flag also consolidate the samples such that the output VCF only has a single SAMPLE column. If you'd like to preserve the sample columns and also have a SUPP, you'd need to create an annotation script to fill in the SUPP flag.

**Comment by jiadong324** [comment]
Thanks for your explanation! It helps a lot!

In terms of the value for ```NumCollapsed```, it will be ```NumCollapsed=1``` for ```chr1 5 ... GT 1/1 0/1``` because only one variants collapsed.

```
>> truvari_merge.vcf
chr1 1 ... GT 0/1 1/1
chr1 5 ... GT 1/1 0/1
```

If what I mentioned above is correct, I further got some results that made me confused. The example below is one record in ```truvari_merge.vcf``` and the ```NumCollapsed=3```. While from the GT columns, I can tell there are two SVs 

```
chr1    2203974 pbsv.DEL.109;DEL00000125        GAGCAGTGCCCACACCCCCAGGTGAGCATCTGACATCGTGGAGCAGCACCCCACACCCACAGGTGAGCATCTGACAGCCTGGAGCAGCACCCACACCCCCAGGTGAGCATCTGACAGCCTGGAACAGCACCCACATCCCCAGGTGAGCCTCTGACATCGTCGAGCAGCACCCCACACCCACAGGTGAGCATCTGACAGCCTGGAACAGCACCCACACCCCCAGGTGAGAATCTGATGTTCTGGAGCATCACACACAACCACAGGTGAGCATCGGAGAGTCTGGAGCAGCACCCACAACCCAAGGTGAGCATCTGACAACCTGGAGCAGCACCCACACCCCGAGGTGAGCATCTGACCTCCCGGAGCAGGACCCATACCTCCAGGCGAGCATCTGAACCCATGGAGCAGCACCCACGCCCCCAGGCGAGCATCTGACCGAACAGAGCAGCACCCACAACCCCATGCGAGCATCTGACAGCCTGGAACAGCACCCACAACCCCAGGTGAGCATCTGACAGCCCGCAGCAGCAACCACACGCACAGGTGAGAATCTGACAGCCCGT     G       635     PASS    SVTYPE=DEL;SVLEN=-562;PRECISE;SVMETHOD=EMBL.DELLYv1.1.8;PE=0;MAPQ=0;CT=3to5;CIPOS=-6,6;CIEND=-6,6;SRMAPQ=42;INSLEN=0;HOMLEN=6;SR=15;SRQ=0.994223;CONSENSUS=CACCCCCAGGGGAGCATCTGAAATCCTGGAGCTGCACCGACAACACCAGGTGAGCATCTGAGAGCCTGGAACAGCACCCGCACCCCCAGGTGAGAATCTGACAGCCTGGAAGAGCACCCCATATCCCCGGGTGAGCATCTGACAGCCTGGAACAGCACCCACTCCCCCAGGTGAGCACCTGACAGACTGGAACAGCACCCACAGGCCCAGGTGAGCCTCTGACAGCTTGGAACAGCACGCGCACCCCCAGGTGAGCATCTGACAGCCTGGAACAGCACCCACACCCCCAGGCGAGCATCTGATAGCCTGGAACAGCACCCACACCCCCAGGAGAGCATCCGGCAGCCTGCAGCAGAACCCACACCAACAGGCGAGCATCTGACAGCCTGGGTCGGCACCCACACCCCCAGGTGAGCATCTGACGGCCTGGAACAGCACCCACACCCCCAGGTGAGCATCTGACATCGTGGAGCAGCACCCCACACCCACAGGTGAGCATCTGACAACCTGGAGCAGCACCCACACCCCCAGGTGAGCATCTGACAGCCTGGAACAGCACCCTGCACCCCCAGGTGAGCATCCGACAGCCTGGAGCAGCAACCACACTCCCAGGCGAGCATCCGATGACCTGGAGCAGCACCCACAACCCCAAGTGAGCATCTGATTTTCTGGAGCAGCACCCACAACCACTGGTGAGCATCGTAGAGTCTGGAGCAGCGCCCACAGCCACAGGCGAGCATCTGACAGCCCGGAGCAGTGCCCACACCCCGAGGTGAGCATCTGACAACAGGGAGCAGCACCCATAGCCCATGGTGAGCACCTGACAACGTGGAGCAGCACCCACACACCCAGGTGAGCATCTGATGGTCTGGAGCAGCACCCACAACCACAGGTGAGCATCGGAGAGTCAGGAGCAGTGCCCACACACCCAGGCGAGCATCTGACAGCCTGGAGCAGCACCCACACCGGCAGGGGAGCATCTGACATCCTGGAGCAGCACCGACAACCCCAGGTGAGCATCTGAGAGCCTGGAACAGCACCCACAACCCCAGGTGAGAATCTGACAGCCTGGAAGAGCACCCCACATCACCGGGTGAGCATCTGACAGCCTGGAACAGCAACCATACCCTCAGGTAAGCATCTGACAGACTGGAACAGCACCCACACGCCCAGGTGAGCCTCTGACAGCCTGGAACAGCACGCGCAACCCCAGGTGAGCATCTGACAGCCTGGAACAGCACCCACACCCACAGGTGAGCATCTGACAGCATGTAACAGCACCCACACCCCCAGGTGAGCATCTGACAGCCTGCAACAGCACCCTGCACCCCCAGGTGCGCACGTGACAGCCTGGAAGAGCACCCACACCCCAAGGCGAGCATCTGACGGCCTGGAACGGCACCCACACCCCCAGGCGAGCATCGGACAGCCTGGAGCAGCACCCCACACCCCCAGGTGAGCATCCGACAGCCTGGAGCAGCACCCACACCCCCAGGTGAGCATGTGACAGCCTGGAAGAGCACCCACACCCCCAGGCGAGCATCTGACAGCCTGGGTCGGCAACCACACACGCAGGTGCGCATCTGATGGTCTGGAGCAGCACCCACACCAACAGGTGAGCATCTGACAGCCTGGAACAGAACCCACACCCCCAGGTGAGCATGTGACAGACTGGAACAGCACCCACATGCCCAGCTGAGCCTCTGACAGCCTGTAACAGCAGCCTGCACCCCCAGGTGCGCCCGTGACAGCCTGGAACAGCACCGACACCCACAGGCGAGCATCTGACGGCCTGGAACAGCACCCACACCCCCAGGTGAGCATTGGACAGCCTGGAGCAGCACCCACAACCCCAGGCGGGCAACCGACAACCTGGAGCAGCACCCACACCCACAGTTGAGCAT;CE=1.8857;CONSBP=952;AC=2;NumCollapsed=3;NumConsolidated=0;CollapseId=73.13 GT:AD:DP:SAC:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV       ./.:.:.:.:.:.:.:.:.:.:.:.:.:.:. 0/1:68,15:83:40,28,11,4:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.:. ./.:.:.:.:.:.:.:.:.:.:.:.:.:.:. 0/1:.:.:.:-80.0277,0,-128.336:10000:PASS:28004:48314:30574:2:0:0:35:21  ./.:.:.:.:.:.:.:.:.:.:.:.:.:.:. ./.:.:.:.:.:.:.:.:.:.:.:.:.:.:.
```

**Comment by ACEnglish** [comment]
You can tie the `CollapseId` to the collapse output's `MatchId` to find the three variants which comprise the three collapsed entries. What you'll likely find is that one of the samples have genotype information in the kept entry and one of the collapsed entries. See the `--gt` [parameter](https://github.com/ACEnglish/truvari/wiki/collapse#--gt) for info no how to allow genotypes from the same sample to prevent variants from matching.

**Comment by jiadong324** [comment]
Awsome, this is really helpful! Thanks a lot!

**Comment by jiadong324** [comment]
Hi Adam,

I tried to unpack the ```SUPP``` for a truvari merged VCF from three callers. I found some records with ```SUPP=0```. For example:

```
chr1    789884  Sniffles2.INS.30S0      A       GTGGAATGTAATGGAATGAAATGGACTCGAATGGAATTAAATGGAATGGAACGGAATGGACTGGG 2       GT   PRECISE;SVTYPE=INS;SVLEN=64;SUPPORT=29;COVERAGE=151,156,159,168,173;STRAND=+-;AF=0.182;STDEV_LEN=0;STDEV_POS=0;SUPPORT_LONG=0;AC=0 GT:GQ:DR:DV:SUPP      0/0:60:130:29:0
```

I am wondering what happened to this SV, since I would expect all SUPP value >0 in the merged VCF. 

Thanks!

**Comment by ACEnglish** [comment]
Populating the SUPP flag involves finding which "samples" have evidence for the presence of the variants. The only signal that's reliable for measuring variant presence is a '1' in the GT. So, if one encounters a situation where there is a VCF entry describing an 'absent' (i.e. reference homozygous) variant, the SUPP flag may become 0. 

Your example variant probably looked similar to the following in the pre-collapse input:
```
chr1    789884  Sniffles2.INS.30S0      A       GTGGAATGTAATGGAATGAAATGGACTCGAATGGAATTAAATGGAATGGAACGGAATGGACTGGG 2       GT   PRECISE;SVTYPE=INS;SVLEN=64;SUPPORT=29;COVERAGE=151,156,159,168,173;STRAND=+-;AF=0.182;STDEV_LEN=0;STDEV_POS=0;SUPPORT_LONG=0;AC=0 GT:GQ:DR:DV:SUPP      ./.:.:.:.:.       0/0:60:130:29:0
```
