### ISSUE TITLE
some questions about the results in fp.vcf.gz 

### ISSUE THREAD

**Issue by xiaomiyongyuan** [ACEnglish/truvari#208]
Hi,
I find some results in fp.vcf.gz are strange,this is an example:

**PctSeqSimilarity=0.9409;PctSizeSimilarity=0.9939;PctRecOverlap=0;SizeDiff=1;StartDistance=-657;EndDistance=-657;GTMatch=1;TruScore=64;MatchId=15.0,15.0 GT 0|1**

this is a varient in fp set ,but you can see the PctSizeSimilarity and PctRecOverlap value are greater than our parameters set(`--pctseq 0.6 --pctsize 0.5`),so if any other parameters in this varient i dont' know are stricted?

`{ "base": "genome/hg002sv_12745/sortbenv0.6.vcf.gz", "comp": "GRCH37/pav/pav_HG002.vcf.gz", "output": "end", "includebed": "genome/v0.6consistent.bed", "extend": 0, "debug": false, "reference": "HG002/GRCH37/hg19.fasta", "refdist": 500, "pctseq": 0.6, "minhaplen": 50, "pctsize": 0.5, "pctovl": 0.0, "typeignore": false, "chunksize": 1000, "bSample": "HG002", "cSample": "HG002", "dup_to_ins": false, "sizemin": 50, "sizefilt": 30, "sizemax": 50000, "passonly": false, "no_ref": false, "pick": "single", "check_monref": true, "check_multi": true } `

Thank you !

**Comment by ACEnglish** [comment]
Is there another tag in the INFO for `Multi`?

```
##INFO=<ID=Multi,Number=0,Type=Flag,Description="Call is false due to non-multimatching">
```

If so, this may indicate that that is another comparison variant nearby that has higher similarity to the baseline variant. This other variant it then 'consuming' the match and causing the example variant to be a false positive. You can control the number of matches variants are allowed to participate in with the `--pick` parameter ([details](https://github.com/ACEnglish/truvari/wiki/bench#controlling-the-number-of-matches)).
