### ISSUE TITLE
Getting same numbers of TP-base and TP-comp

### ISSUE THREAD

**Issue by poddarharsh15** [ACEnglish/truvari#210]
Hi @ACEnglish,

I'm running Truvari on several SV callers, and for some results, I'm getting the same numbers of variants in tpbase and tpcomp. Is this expected, or should I be concerned?

Thanks,

> 2024-04-08 11:13:42,972 [INFO] Truvari v4.2.3.dev0+a8dbd30
2024-04-08 11:13:42,972 [INFO] Command /home/tigem/h.poddar/anaconda3/bin/truvari bench -b /home/tigem/h.poddar/HG002_WGS_150/no_duplicates/HG002_deletions.vcf.gz -c lumpy_sorted_del.vcf.gz --includebed HG002_SVs.bed -f /home/tigem/h.poddar/short_reads_pipeline/reference_genome/GRCh37/GRCh37.p13.genome.fa --pctseq 0 -C 1000 -P 0 -s 50 --sizemax 260000000 -S 50 -r 1000 --pick multi --dup-to-ins --passonly -o lumpy_del
2024-04-08 11:13:42,972 [INFO] Params:
{
    "base": "/home/tigem/h.poddar/HG002_WGS_150/no_duplicates/HG002_deletions.vcf.gz",
    "comp": "/home/tigem/h.poddar/HG002_WGS_150/no_duplicates/140609_D00360_0023_BH9UD5ADXX/bwamem/lumpy_sorted_del.vcf.gz",
    "output": "lumpy_del",
    "includebed": "/home/tigem/h.poddar/HG002_WGS_150/no_duplicates/140609_D00360_0023_BH9UD5ADXX/bwamem/HG002_SVs.bed",
    "extend": 0,
    "debug": false,
    "reference": "/home/tigem/h.poddar/short_reads_pipeline/reference_genome/GRCh37/GRCh37.p13.genome.fa",
    "refdist": 1000,
    "pctseq": 0.0,
    "minhaplen": 50,
    "pctsize": 0.0,
    "pctovl": 0.0,
    "typeignore": false,
    "chunksize": 1000,
    "bSample": "HG002",
    "cSample": "HG002",
    "dup_to_ins": true,
    "sizemin": 50,
    "sizefilt": 50,
    "sizemax": 260000000,
    "passonly": true,
    "no_ref": false,
    "pick": "multi",
    "check_monref": true,
    "check_multi": true
}
2024-04-08 11:13:43,276 [INFO] Including 34830 bed regions
2024-04-08 11:13:44,277 [INFO] Zipped 12336 variants Counter({'base': 10159, 'comp': 2177})
2024-04-08 11:13:44,277 [INFO] 4338 chunks of 12336 variants Counter({'__filtered': 6028, 'base': 4203, 'comp': 2105})
2024-04-08 11:13:44,945 [INFO] Stats: {
    "TP-base": 1977,
    "TP-comp": 1977,
    "FP": 128,
    "FN": 2226,
    "precision": 0.9391923990498813,
    "recall": 0.470378301213419,
    "f1": 0.6268230818008879,
    "base cnt": 4203,
    "comp cnt": 2105,
    "TP-comp_TP-gt": 0,
    "TP-comp_FP-gt": 1977,
    "TP-base_TP-gt": 0,
    "TP-base_FP-gt": 1977,
    "gt_concordance": 0.0,
    "gt_matrix": {
        "(0, 1)": {
            "(None, None)": 1126
        },
        "(1, 1)": {
            "(None, None)": 851
        }
    }
}
2024-04-08 11:13:44,945 [INFO] Finished bench

**Comment by ACEnglish** [comment]
According to that log Truvari executed the task successfully.

**Comment by poddarharsh15** [comment]
Hi @ACEnglish,

Is there a better method to convert summary files into data frames for benchmarking purposes?

Thank you

**Comment by ACEnglish** [comment]
the summary is a json file. json to pandas dataframes is possible. `truvari vcf2df` also can convert the benchmarking output vcfs to dataframes.

**Comment by poddarharsh15** [comment]
[truvari_results.txt](https://github.com/ACEnglish/truvari/files/14930514/truvari_results.txt)
Is there a way to convert these results into a dataframe format for benchmarking purposes? I'm working with 10 flow cells, using 5 SV callers and 3 aligners, and need to calculate averages to plot a Precision-Recall graph. Thank you.
