### ISSUE TITLE
Inquiry on the Determination of Representative Structural Variants in Merged VCF Sets

### ISSUE THREAD

**Issue by Flooooooooooooower** [ACEnglish/truvari#215]
Hi ,

Thanks for your tool, and I try to test in my research.

I am attempting to merge multiple VCF sets from a sample, including sets from SVIM, cuteSV, SVision, Debreak, and Sniffles. However, I am unclear about how the representative structural variants (SVs) are determined in the output VCF set. I have observed that Sniffles2 is frequently chosen as the representative in many cases. Could you please explain if there is a specific reason for this preference?

Best wishes

**Comment by ACEnglish** [comment]
The representative variant is determined by the `--choose` parameter 

https://github.com/ACEnglish/truvari/wiki/collapse#--choose-behavior

**Comment by Flooooooooooooower** [comment]
I apologize for my oversight.
Best wishes
