### ISSUE TITLE
INFO/END field not carried through from input VCF to output VCF

### ISSUE THREAD

**Issue by juniper-lake** [ACEnglish/truvari#222]
**Version** : 

Truvari v4.2.2

**Describe the bug** : 

In `truvari collapse` the `INFO/END` field is not carried through from input VCF to output VCFs (either main output or collapsed output). However, the header line `##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the structural variant described in this record”>` is still present in the output VCFs. I can recalculate the `INFO/END` from `INFO/SVLEN` and `INFO/SVTYPE` or use `bcftools annotate` to pull them from input VCF but it’s an annoying extra step.

**To Reproduce** : 

```
truvari collapse --input input.vcf.gz \
  --sizemin 20 \
  --refdist 0 \
  --pctseq 0 \
  --pctsize 0.95 \
  --collapsed-output collapsed_output.vcf \
  --output output.vcf
```

**Expected behavior** : 

I expected all `INFO` fields to be carried through from input VCF to output VCFs dependent on the `--keep` behavior.

**Example Data** : 

Before using `truvari collapse` (format fields redacted):

```
chrX    230292  2_1_pbsv.DEL.0_duplicate6       AGCTCCTCCCCTCGGGACCACCCCAGACCCCCGCTCCTCCCCTCGGGACCACCCCCAGACCCCCTGCTCCTCCTCTTAGGACCATCCCCAGACCCCCCCTTCTACCCACGGGACCACACCCAGAACCCCCAGCTCCTCCCCTCGGGACCACCCCAGACCCCCGCTCCTCCCCTCGGGACCACCCCCAGACCCCCTGCTCCTCCCCTCGGGACCACCCCAGACCCCCGCTCCTCCCCTCGGGACCACCCCAGACCCCCGCTCCTCCCCTCGGGACCACCCCCAGACCCCCTGCTCCTCCTCTTAGGACCATCCCCAGACCCCCCCTCCTACCCACGGGACCACACCCAGAACCCCCAGCTCCTCCCCTCGGGACCACCTCAGACCCCCGCTCCTCCCCTCGGGACCACCCCAGACCCCCGCTCCTCCCCTCGGGACCACCCCCAGACCCCCTGCTCCTCCTCTTAGGACCATCCCCAGACCCCCCCTCCTACCCACGGGACCACACCCAGAACCCCCAGCTCCTCCCCTCGGGACCACACCCAGACCCCCCCTCCTACCCACGGGACCACACCCAGAACCCCCAGCTCCTCCCCTCGGGACCACCCCAGACCCCC  A       .       PASS    SVTYPE=DEL;END=230905;SVLEN=-613;SVANN=TANDEM;STARTVARIANCE=1406.250000;ENDVARIANCE=7310.250000;AVG_LEN=-709.000000;AVG_START=230329.500000;AVG_END=230990.500000;VARCALLS=11;ALLVARS_EXT=((pbsv.DEL.0),(pbsv.DEL.3_duplicate13),(pbsv.DEL.3_duplicate10),(pbsv.DEL.2_duplicate11),(pbsv.DEL.0_duplicate9,pbsv.DEL.1_duplicate9),(pbsv.DEL.3_duplicate8),(pbsv.DEL.3_duplicate12),(pbsv.DEL.2_duplicate8)),((pbsv.DEL.2),(pbsv.DEL.4_duplicate9));SUPP_VEC_EXT=000100000000000001000000000010000000000000000000001000000000000000010000000000000000000000000000010000000000100100000000000000110000000;IDLIST_EXT=pbsv.DEL.0_duplicate6,pbsv.DEL.3_duplicate13,pbsv.DEL.3_duplicate10,pbsv.DEL.2_duplicate11,pbsv.DEL.0_duplicate9,pbsv.DEL.3_duplicate8,pbsv.DEL.3_duplicate12,pbsv.DEL.2_duplicate8,pbsv.DEL.2_duplicate8,pbsv.DEL.4_duplicate9;SUPP_EXT=10;SUPP_VEC=00100100;SUPP=2;SVMETHOD=JASMINE;IDLIST=1_pbsv.DEL.0_duplicate6,11_pbsv.DEL.2_duplicate8;INTRASAMPLE_IDLIST=pbsv.DEL.0_duplicate6.pbsv.DEL.3_duplicate13.pbsv.DEL.3_duplicate10.pbsv.DEL.2_duplicate11.pbsv.DEL.0_duplicate9,pbsv.DEL.1_duplicate9.pbsv.DEL.3_duplicate8.pbsv.DEL.3_duplicate12.pbsv.DEL.2_duplicate8
```

After using `truvari collapse`:

```
chrX    230292  2_1_pbsv.DEL.0_duplicate6       AGCTCCTCCCCTCGGGACCACCCCAGACCCCCGCTCCTCCCCTCGGGACCACCCCCAGACCCCCTGCTCCTCCTCTTAGGACCATCCCCAGACCCCCCCTTCTACCCACGGGACCACACCCAGAACCCCCAGCTCCTCCCCTCGGGACCACCCCAGACCCCCGCTCCTCCCCTCGGGACCACCCCCAGACCCCCTGCTCCTCCCCTCGGGACCACCCCAGACCCCCGCTCCTCCCCTCGGGACCACCCCAGACCCCCGCTCCTCCCCTCGGGACCACCCCCAGACCCCCTGCTCCTCCTCTTAGGACCATCCCCAGACCCCCCCTCCTACCCACGGGACCACACCCAGAACCCCCAGCTCCTCCCCTCGGGACCACCTCAGACCCCCGCTCCTCCCCTCGGGACCACCCCAGACCCCCGCTCCTCCCCTCGGGACCACCCCCAGACCCCCTGCTCCTCCTCTTAGGACCATCCCCAGACCCCCCCTCCTACCCACGGGACCACACCCAGAACCCCCAGCTCCTCCCCTCGGGACCACACCCAGACCCCCCCTCCTACCCACGGGACCACACCCAGAACCCCCAGCTCCTCCCCTCGGGACCACCCCAGACCCCC  A       .       PASS    SVTYPE=DEL;SVLEN=-613;SVANN=TANDEM;STARTVARIANCE=1406.250000;ENDVARIANCE=7310.250000;AVG_LEN=-709.000000;AVG_START=230329.500000;AVG_END=230990.500000;VARCALLS=11;ALLVARS_EXT=((pbsv.DEL.0),(pbsv.DEL.3_duplicate13),(pbsv.DEL.3_duplicate10),(pbsv.DEL.2_duplicate11),(pbsv.DEL.0_duplicate9,pbsv.DEL.1_duplicate9),(pbsv.DEL.3_duplicate8),(pbsv.DEL.3_duplicate12),(pbsv.DEL.2_duplicate8)),((pbsv.DEL.2),(pbsv.DEL.4_duplicate9));SUPP_VEC_EXT=000100000000000001000000000010000000000000000000001000000000000000010000000000000000000000000000010000000000100100000000000000110000000;IDLIST_EXT=pbsv.DEL.0_duplicate6,pbsv.DEL.3_duplicate13,pbsv.DEL.3_duplicate10,pbsv.DEL.2_duplicate11,pbsv.DEL.0_duplicate9,pbsv.DEL.3_duplicate8,pbsv.DEL.3_duplicate12,pbsv.DEL.2_duplicate8,pbsv.DEL.2_duplicate8,pbsv.DEL.4_duplicate9;SUPP_EXT=10;SUPP_VEC=00100100;SUPP=2;SVMETHOD=JASMINE;IDLIST=1_pbsv.DEL.0_duplicate6,11_pbsv.DEL.2_duplicate8;INTRASAMPLE_IDLIST=pbsv.DEL.0_duplicate6.pbsv.DEL.3_duplicate13.pbsv.DEL.3_duplicate10.pbsv.DEL.2_duplicate11.pbsv.DEL.0_duplicate9,pbsv.DEL.1_duplicate9.pbsv.DEL.3_duplicate8.pbsv.DEL.3_duplicate12.pbsv.DEL.2_duplicate8;NumCollapsed=1;NumConsolidated=0;CollapseId=9.3
```

**Additional context** :

Input VCF was already merged with Jasmine before using `truvari collapse`.

**Comment by ACEnglish** [comment]
Hello,

I also observed this behavior some time ago and was worried it was a bug. However, I found that the [VCF format specification](https://samtools.github.io/hts-specs/VCFv4.2.pdf) states: 
```
• END : end position of the variant described in this record (for use with symbolic alleles)
```
The key being 'use with symbolic alleles'. END isn't needed for sequence resolved SVs as it can be imputed from "END is POS + length of REF allele - 1"

The `INFO/END` tag is dropped automatically by Truvari's vcf parser `pysam` which is a python binding of the core `htslib` which is from the same maintainers of the VCF format specification.

All that is to say: Truvari isn't dropping it, but the VCF format is dropping it, and there are no exposed pysam parameters I'm aware of to force it to not 'correct' vcf entries.

Have a great day,
~/Adam English

Note on the additional context: We recommend using the output from`bcftools merge` for `truvari collapse` as it preserves all variant representations. Running jasmine and then truvari is essentially a double merge/collapsing (e.g. running  `truvari collapse --pctseq/--pctsize 0.90` and then `truvari collapse --pctseq/pctsize 0.95`. (assuming default parameters))

**Comment by ACEnglish** [comment]
One more note that may be helpful: most vcf parsers will automatically populate the END. For example: `bcftools query -f "%END\n" vcf_without_info_end_tag.vcf.gz` or pysam's `VariantRecord` object having a `stop` attribute. I don't know what your downstream pipeline uses, but most tooling will do fine without END, so `bcftools annotate` can hopefully be skipped.

**Comment by juniper-lake** [comment]
Thanks for the thorough response!
