### ISSUE TITLE
Collapsed INFO column

### ISSUE THREAD

**Issue by jiadong324** [ACEnglish/truvari#225]
**Version** : v4.2.1

I am wondering whether the INFO column in the collapsed VCF is the concatenation all INFOs of every collapsed variants. I also saw the ID column of collapsed VCF concatinates every collapsed variant ID. 

It was weried that when I used the same command to another set of samples, the INFO and ID column of collapsed only keeps one of the collapsed variants instead of concatenating them together

```
truvari collapse -i {input.bcfvcf} -c {output.removed} --sizemin 0 --sizemax 1000000 -k maxqual --gt het --intra --pctseq 0.90 --pctsize 0.90 --refdist 500 
```

**Comment by ACEnglish** [comment]
INFO and ID fields are not manipulated by collapse. Any changes you've observed are likely caused by the pre-processing step of `bcftools merge`.
