### ISSUE TITLE
Issue with MAMnet and Truvari Collapse Parameter Optimization

### ISSUE THREAD

**Issue by Flooooooooooooower** [ACEnglish/truvari#227]
Hi,

Recently, I've been using different SV caller software to evaluate their F1-scores. However, when using the MAMnet software, I couldn't get any results. Could you please suggest a solution for this issue?

Additionally, I have another question. When merging the SV results from multiple software tools using Truvari collapse, do you have any recommended parameters? I tried using the default parameters, but the F1-score was around 0.5.

[HG002.HIFI_lra_MAMnet.vcf.gz](https://github.com/user-attachments/files/16694465/HG002.HIFI_lra_MAMnet.vcf.gz)

**Comment by ACEnglish** [comment]
The provided VCF seems to be poorly formatted. All the REF and ALT columns have a dot ('.') value. A dot in the ALT field indicates a 'monomorphic reference' site i.e. there is no variant at this position, which are filtered by truvari. At minimum, the VCF entries need to be reformatted to include a REF anchor base of N and an ALT of the symbolic allele (e.g. <INS>). See https://samtools.github.io/hts-specs/VCFv4.5.pdf for details.

Truvari collapse's default parameters are the recommended parameters as they work generally well in an average use-case. However, as the resolution and representation of variants can differ wildly between callers, the average use-case isn't necessarily the best fit for your experiment. You'll need to explore your variants and understand truvari's core comparison engine's [matching parameters](https://github.com/ACEnglish/truvari/wiki/bench#matching-parameters) as well as the [collapse specific parameters](https://github.com/ACEnglish/truvari/wiki/collapse) to create an optimized result.
