### ISSUE TITLE
"Permission denied: Unknown error" when running truvari in HPC environment

### ISSUE THREAD

**Issue by xander-ho** [ACEnglish/truvari#230]
Hello,

I'm encountering an error very similar to that outlined earlier this week:

https://github.com/ACEnglish/truvari/issues/229

Have you got any advice for this error where setting TMPDIR doesn't resolve the issue? I have tried running truvari both through a container (using the provided Dockerfile) and through a direct conda installation on our HPC. I've verified that the container can write to the directories specified by -o and the configured TMPDIR, so I'm wondering if there is another location that needs to be rw accessible? 

Best,
Alex

**Comment by ACEnglish** [comment]
Every encounter I've had with the error as described in the previous ticket was solved by setting the TMPDIR. So I assume your error must be different. At what point in the logs does the error happen? Is there any reason to believe that your VCF is malformed? Is this happening with bench or other commands?

**Comment by xander-ho** [comment]
Hello,

You are correct that the root cause was indeed the TMPDIR. There is some weird permissions layer on our scratch location that allowed me to write there interactively through the container but not via truvari bench. Please feel free to resolve the issue and apologies for wasting your time!

Best,
Alex
