### ISSUE TITLE
Equivalent to giabreport

### ISSUE THREAD

**Issue by Tintest** [ACEnglish/truvari#235]
Hello,

A few years ago, I used Truvari with the ```-giabreport``` parameter, which was very useful for stratifying results by SV type. Unfortunately, this parameter doesn't seem to be available in ```truvari bench``` from ```Truvari v4.3.0``` and I can't find any equivalent. Am I missing something? This parameter seems to have disappeared relatively recently. Is there a particular reason for this?

Thank you very much.

**Comment by ACEnglish** [comment]
That parameter was deprecated for a few reasons.
1. It's been replaced by advanced parsing that would allow users more customization of their reports via `truvari vcf2df` and [recipes](https://github.com/ACEnglish/truvari/discussions/categories/vcf2df-recipes) using that dataframe.
2. The giabreport only worked with GIAB v0.6 specific annotations which aren't available for newer, more comprehensive benchmarks such as [GIAB v1.1](https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/NIST_HG002_DraftBenchmark_defrabbV0.018-20240716/)
3. That old functionality was placed in another tool, [laytr](https://github.com/ACEnglish/laytr), though admittedly that tool is behind on documentation/support.
