### ISSUE TITLE
Issue while trying to run collapse using trivari

### ISSUE THREAD

**Issue by akhilpampana** [ACEnglish/truvari#236]
**Version** : 
Truvari v3.2.0

**Describe the bug** : 

I am trying to run Truvari using the latest version and v3.2.0 and I am getting 'invalid FORMAT: SR' error.

**To Reproduce** : 
Merged the files using bcftools - bcftools merge -m none --file-list "$in_prefix".in -Oz -o "$in_prefix".merged.vcf.gz --threads 72
Index and truvari run - truvari collapse -i "$in_prefix".vcf.gz -o test.vcf -c collsed.vcf --reference Homo_sapiens_assembly38.fasta
reference file downloaded from here: https://console.cloud.google.com/storage/browser/genomics-public-data/resources/broad/hg38/v0

**Expected behavior** : 
It should generate a collapsed vcf file.

**Comment by ACEnglish** [comment]
Is truvari throwing the error or bcftools throwing the error? 

Regardless, the error is pretty informative and it's indicating that there is problem with the 'SR' format. Are you certain that the input VCF, and specifically the SR field, is valid?

**Comment by akhilpampana** [comment]
Truvari is throwing the error. There are lot of missingness and I suspect that could be the reason for the issue. Is there a way to fix this?

**Comment by ACEnglish** [comment]
Interesting. Truvari doesn't use an SR field, so that error must be coming from pysam which thinks SR is broken. You can try to remove it with `bcftools annotate -x FORMAT/SR`

**Comment by akhilpampana** [comment]
Got it. Thank you so much for the response. I will see and let you know.
