### ISSUE TITLE
Processing vcf files in BED format

### ISSUE THREAD

**Issue by zhujiahua700403** [ACEnglish/truvari#241]
Thank you for your contribution.
Your software has helped me a lot, however, it would be nice if you could make truvari compatible with the output of bed formats (e.g. gridss, svaba, etc.) or provide code that can convert such files. It would help with future research and I hope you will consider my suggestion!
Thank you!

**Comment by ACEnglish** [comment]
Hello,

I'm happy to hear that Truvari has been useful to you. 

There are currently no development plans to incorporate bed format parsing of variants into Truvari. The VCF is the de-facto standard for variant representations, and all our development effort is around ensuring Truvari can handle all of a VCF's idiosyncrasies. However, you may be able to find or create a bed to VCF conversion script, or request VCF outputs from the developers of the callers you're interested in.

Have a great day,
~/Adam English
