### ISSUE TITLE
Information about truvari collapse output!!! 

### ISSUE THREAD

**Issue by poddarharsh15** [ACEnglish/truvari#251]
2024-12-18 11:34:06,792 [INFO] Truvari v4.1.0
2024-12-18 11:34:06,792 [INFO] Command /home/tigem/h.poddar/miniconda3/envs/truvari/bin/`truvari collapse -i /home/tigem/h.poddar/AF_Calculation/Population_vcf/all_cohort_vcfs_merged.filtered.vcf.gz -o /home/tigem/h.poddar/AF_Calculation/Population_vcf/truvari_merged.vcf -c /home/tigem/h.poddar/AF_Calculation/Population_vcf/truvari_collapsed.vcf -f /home/tigem/h.poddar/structural_varinats/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta -k first -s 50 -S 10000000 --passonly -B 50 -r 1000 -p 0 -P 0.5 -O 0.5 --chain --typeignore`

> 2024-12-18 11:34:06,792 [INFO] Params:
> {
>     "input": "/home/tigem/h.poddar/AF_Calculation/Population_vcf/all_cohort_vcfs_merged.filtered.vcf.gz",
>     "output": "/home/tigem/h.poddar/AF_Calculation/Population_vcf/truvari_merged.vcf",
>     "collapsed_output": "/home/tigem/h.poddar/AF_Calculation/Population_vcf/truvari_collapsed.vcf",
>     "reference": "/home/tigem/h.poddar/structural_varinats/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta",
>     "keep": "first",
>     "median_info": false,
>     "debug": false,
>     "refdist": 1000,
>     "pctseq": 0.0,
>     "minhaplen": 50,
>     "pctsize": 0.5,
>     "pctovl": 0.5,
>     "typeignore": true,
>     "use_lev": false,
>     "hap": false,
>     "chain": true,
>     "no_consolidate": true,
>     "null_consolidate": null,
>     "sizemin": 50,
>     "sizemax": 10000000,
>     "passonly": true,
>     "chunksize": 1000,
>     "bSample": null,
>     "cSample": null,
>     "sizefilt": 50,
>     "no_ref": false
> }
> 2024-12-18 23:18:45,724 [INFO] Zipped 2852604 variants Counter({'base': 2852604})
> 2024-12-18 23:18:45,913 [INFO] 153154 chunks of 2852604 variants Counter({'base': 2796753, '__filtered': 55851})
> 2024-12-18 23:18:46,170 [INFO] Wrote 469133 Variants
> 2024-12-18 23:18:46,180 [INFO] 12552992 variants collapsed into 263817 variants
> 2024-12-18 23:18:46,180 [INFO] 3372980 samples' FORMAT fields consolidated
> 2024-12-18 23:18:46,180 [INFO] Finished collapse

     
Hi @ACEnglish,

Sorry for the confusion, but I’m a bit unsure about the outputs from truvari: specifically, the difference between `truvari_merged.vcf` and `truvari_collapsed.vcf`. Based on the literature and other discussions, my understanding is that the variants in the collapsed output (truvari_collapsed.vcf) are not the common variants, but rather those that didn’t merge due to differences — is that correct?

I suspect that the parameters I used to merge my VCF files (N=441) might have been too stringent, which resulted in too many variants ending up in the collapsed output. Could you help clarify this?

Ultimately, my goal is to use the merged VCF file as a population database to filter out common variants from my proband VCFs, keeping only the rare ones. I’d appreciate any guidance you have!

Thanks a lot in advance!

**Comment by poddarharsh15** [comment]
Thank you so much for the explanation.

**Comment by poddarharsh15** [comment]
Hi @ACEnglish,

Apologies for reopening this thread, but I thought it would be easier to follow up here for clarity. Based on our earlier discussions, I’ve understood how the collapsed output functions. However, after updating to the latest version of Truvari, I’ve noticed some changes when running the same parameters. Specifically, the `"minhaplen": 50` tag seems to have been removed in the new version, and it now emits errors when I try to use it.

To help illustrate, I’m adding two test runs I’ve performed with identical parameters, which should highlight the differences between versions. Could you take a look and provide some insights?

Thanks so much for your help and any suggestions you might have! :)


**Truvari v4.1.0**

```
truvari collapse -i /home/tigem/h.poddar/AF_Calculation/Population_truvari/all_cohort_vcfs_merged.filtered.vcf.gz -o truvari_merged.vcf -c truvari_collapsed.vcf -f $ref.fasta -k common -s 50 -S 10000000 --passonly -B 50 -r 1000 -p 0.9 -P 0.3 -O 0.3 --chain --typeignore

[INFO] Params:
{
    "input": "/home/tigem/h.poddar/AF_Calculation/Population_truvari/all_cohort_vcfs_merged.filtered.vcf.gz",
    "output": "/home/tigem/h.poddar/AF_Calculation/Population_truvari/truvari_merged.vcf",
    "collapsed_output": "/home/tigem/h.poddar/AF_Calculation/Population_truvari/truvari_collapsed.vcf",
    "reference": "/home/tigem/h.poddar/structural_varinats/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta",
    "keep": "common",
    "median_info": false,
    "debug": false,
    "refdist": 1000,
    "pctseq": 0.9,
    "minhaplen": 50,
    "pctsize": 0.3,
    "pctovl": 0.3,
    "typeignore": true,
    "use_lev": false,
    "hap": false,
    "chain": true,
    "no_consolidate": true,
    "null_consolidate": null,
    "sizemin": 50,
    "sizemax": 10000000,
    "passonly": true,
    "chunksize": 1000,
    "bSample": null,
    "cSample": null,
    "sizefilt": 50,
    "no_ref": false
}
2024-12-19 18:13:27,991 [WARNING] Unresolved SVs (e.g. ALT=<DEL>) are filtered when `--pctseq != 0`
2024-12-19 18:40:20,116 [INFO] Zipped 2852604 variants Counter({'base': 2852604})
2024-12-19 18:40:20,121 [INFO] 836 chunks of 2852604 variants Counter({'__filtered': 2850762, 'base': 1842})
2024-12-19 18:40:58,510 [INFO] Wrote 2851954 Variants
2024-12-19 18:40:58,510 [INFO] 2147 variants collapsed into 317 variants
2024-12-19 18:40:58,511 [INFO] 1579 samples' FORMAT fields consolidated
2024-12-19 18:40:58,511 [INFO] Finished collapse
```


**Truvari v5.0.0**

```
truvari collapse -i /home/tigem/h.poddar/AF_Calculation/Population_truvari/all_cohort_vcfs_merged.filtered.vcf.gz -o truvari_merged.vcf -c truvari_collapsed.vcf -f $ref.fasta -k common -s 50 -S 10000000 --passonly -r 1000 -p 0.9 -P 0.3 -O 0.3 --chain --typeignore


{
    "input": "/home/tigem/h.poddar/AF_Calculation/FINAL_POPULATION/all_cohort_vcfs_merged.filtered.vcf.gz",
    "output": "/home/tigem/h.poddar/AF_Calculation/FINAL_POPULATION/truvari_merged.vcf",
    "removed_output": "/home/tigem/h.poddar/AF_Calculation/FINAL_POPULATION/truvari_removed.vcf",
    "reference": "/home/tigem/h.poddar/structural_varinats/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta",
    "write_resolved": false,
    "keep": "common",
    "bed": null,
    "gt": "off",
    "intra": false,
    "median_info": false,
    "debug": false,
    "refdist": 1000,
    "pctseq": 0.9,
    "pctsize": 0.3,
    "pctovl": 0.3,
    "typeignore": true,
    "no_roll": true,
    "max_resolve": 25000,
    "decompose": false,
    "hap": false,
    "chain": true,
    "no_consolidate": true,
    "sizemin": 50,
    "sizemax": 10000000,
    "passonly": true
}
2025-01-13 21:01:35,011 [INFO] Zipped 2852588 variants Counter({'base': 2852588})
2025-01-13 21:01:35,012 [INFO] 148971 chunks of 2852588 variants Counter({'base': 2796739, '__filtered': 55849})
2025-01-13 21:01:35,113 [INFO] Wrote 335319 Variants
2025-01-13 21:01:35,113 [INFO] 2517269 variants collapsed into 219909 variants
2025-01-13 21:01:35,113 [INFO] 2975182 samples' FORMAT fields consolidated
2025-01-13 21:01:35,113 [INFO] Finished collapse
```

**Comment by ACEnglish** [comment]
V5 is a major version bump because we've made a number of breaking changes, including deprecating the old "reference context" sequence comparison , which was the only thing using min hap len. That approach was slower and less accurate.

**Comment by ACEnglish** [comment]
Sorry, I also didn't look closely at the logs. The other big change is that `--pctseq != 0` no longer prevents truvari from comparing / collapsing symbolic variants. Your VCF seems to have a lot of symbolic variants which were previously being ignored, but with v5 are being collapsed, thus the change in final variant count from 2.8M (2.1K collapsed) to 335K (2.5M collapsed)

**Comment by poddarharsh15** [comment]
Hi @ACEnglish,

Thanks for the clarification. Yes, in my case, all the variants across the multiple VCF files (N=441 samples) are symbolic variants, such as <DEL>, <DUP>, <INS>, and so on. My primary aim was to merge all these variants into a single population VCF and use this as a reference to filter out common variants from a singular proband's VCF using `bcftools isec`. Following that, I planned to prioritize the rare variants in each proband's VCF for downstream analysis.

However, I'm a bit lost when I see different numbers of merged variants produced by Truvari between versions, especially with symbolic variants being handled differently. I’m unsure which output would be more appropriate to use as the population VCF for my workflow. I hope I’ve managed to explain my objective clearly—please let me know if further details would help clarify.

Thanks again for your guidance!

**Comment by poddarharsh15** [comment]
Hi @ACEnglish,

Thanks for the clarification. Yes, in my case, all the variants across the multiple VCF files (N=441 samples) are symbolic variants, such as  `<DEL> <DUP> <INS>` , and so on. My primary aim was to merge all these variants into a single population VCF and use this as a reference to filter out common variants from a singular proband's VCF using `bcftools isec`. Following that, I planned to prioritize the rare variants in each proband's VCF for downstream analysis.

However, I'm a bit lost when I see different numbers of merged variants produced by Truvari between versions, especially with symbolic variants being handled differently. I’m unsure which output would be more appropriate to use as the population VCF for my workflow. I hope I’ve managed to explain my objective clearly—please let me know if further details would help clarify.

Thanks again for your guidance!

**Comment by ACEnglish** [comment]
Remove type ignore.
Remove pct ovl
Set size sim to .9
Experiment with chain
Use V5
You'll probably make a better result.
Compare variant counts and AF distribution of the runs and do QC to figure out what you like. The above params are just a starting point

**Comment by ACEnglish** [comment]
And I'm unfamiliar with isec. Test truvari bench -b pop.vcf -c proband.vcf -f ref.fa -o result

Proband specific will be in result/fp.vcf.gz

Again, experiment and test.
